#!/bin/bash
# =============================================================================
# Office Tools — Deploy Manager
# Interactive menu for installation, domain management, and removal.
#
# Supports:  Debian · Ubuntu · AlmaLinux · Rocky Linux · CentOS Stream
# Usage:     sudo bash deploy.sh
# =============================================================================

# ─── Colors & helpers ─────────────────────────────────────────────────────────
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'
CYAN='\033[0;36m'; BOLD='\033[1m'; DIM='\033[2m'; RESET='\033[0m'

info()    { echo -e "${CYAN}[INFO]${RESET}  $*"; }
success() { echo -e "${GREEN}[OK]${RESET}    $*"; }
warn()    { echo -e "${YELLOW}[WARN]${RESET}  $*"; }
die()     { echo -e "${RED}${BOLD}[FATAL]${RESET} $*" >&2; exit 1; }

section() {
    echo ""
    echo -e "${BOLD}${CYAN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${RESET}"
    echo -e "${BOLD}${CYAN}  $*${RESET}"
    echo -e "${BOLD}${CYAN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${RESET}"
    echo ""
}

press_enter() {
    echo ""
    echo -ne "${DIM}  Press Enter to return to menu…${RESET}"
    read -r
}

# Returns 0 (true=proceed) or 1 (abort — n or 0 pressed)
ask_proceed() {
    local prompt="${1:-Proceed}"
    echo -ne "  ${BOLD}${prompt}? [Y/n/0]: ${RESET}"; read -r _ap
    [[ "${_ap,,}" == "n" || "$_ap" == "0" ]] && return 1
    return 0
}

# ─── Paths ────────────────────────────────────────────────────────────────────
REPO_URL="https://github.com/noobvie/Office_Tools.git"
REPO_DIR="/opt/office-tools/repo"
WEB_ROOT="/var/www/office-tools"
BACKEND_DIR="/opt/office-tools/backend"
PB_DIR="/opt/office-tools/pocketbase"
DEPLOY_CONF="/opt/office-tools/deploy.conf"
LOG_DIR="/var/log/office-tools"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# nginx config paths — set by detect_os()
NGINX_CONF_PATH=""
NGINX_ENABLED_PATH=""   # empty = not used (RHEL writes directly to conf.d)

# ─── OS detection ─────────────────────────────────────────────────────────────
OS_FAMILY=""   # "debian" or "rhel"
OS_NAME="unknown"

detect_os() {
    if [[ ! -f /etc/os-release ]]; then
        die "Cannot detect OS (/etc/os-release not found)."
    fi
    # shellcheck source=/dev/null
    source /etc/os-release
    OS_NAME="${PRETTY_NAME:-${NAME:-unknown}}"

    case "${ID:-}" in
        ubuntu|debian|linuxmint|pop)
            OS_FAMILY="debian" ;;
        almalinux|rocky|centos|rhel|fedora|ol)
            OS_FAMILY="rhel" ;;
        *)
            case "${ID_LIKE:-}" in
                *debian*) OS_FAMILY="debian" ;;
                *rhel*|*centos*|*fedora*) OS_FAMILY="rhel" ;;
                *) die "Unsupported OS: ${OS_NAME}. Use Debian/Ubuntu or AlmaLinux/Rocky Linux." ;;
            esac ;;
    esac

    if [[ "$OS_FAMILY" == "debian" ]]; then
        NGINX_CONF_PATH="/etc/nginx/sites-available/office-tools"
        NGINX_ENABLED_PATH="/etc/nginx/sites-enabled/office-tools"
    else
        NGINX_CONF_PATH="/etc/nginx/conf.d/office-tools.conf"
        NGINX_ENABLED_PATH=""
    fi
}

# ─── Config helpers ────────────────────────────────────────────────────────────
DOMAIN=""; EMAIL=""; SETUP_BACKEND="n"; PB_ADMIN_EMAIL=""

load_conf() {
    DOMAIN=""; EMAIL=""; SETUP_BACKEND="n"; PB_ADMIN_EMAIL=""
    [[ -f "$DEPLOY_CONF" ]] && source "$DEPLOY_CONF" || true
}

save_conf() {
    mkdir -p "$(dirname "$DEPLOY_CONF")"
    cat > "$DEPLOY_CONF" << CONFEOF
# Office Tools deploy config — auto-generated by deploy.sh
DOMAIN="${DOMAIN}"
EMAIL="${EMAIL}"
SETUP_BACKEND="${SETUP_BACKEND}"
PB_ADMIN_EMAIL="${PB_ADMIN_EMAIL}"
CONFEOF
    chmod 600 "$DEPLOY_CONF"
}

# ─── Package management ────────────────────────────────────────────────────────
pkg_update_os() {
    section "Updating OS packages — ${OS_NAME}"
    if [[ "$OS_FAMILY" == "debian" ]]; then
        apt-get update -qq
        DEBIAN_FRONTEND=noninteractive apt-get upgrade -y
    else
        dnf upgrade -y --nobest 2>/dev/null || dnf upgrade -y
    fi
    success "OS packages updated"
}

pkg_install() {
    if [[ "$OS_FAMILY" == "debian" ]]; then
        apt-get install -y --no-install-recommends "$@"
    else
        dnf install -y "$@"
    fi
}

install_base_packages() {
    section "Installing base packages"
    if [[ "$OS_FAMILY" == "debian" ]]; then
        apt-get update -qq
        pkg_install nginx certbot python3-certbot-nginx \
            git curl unzip rsync ca-certificates gnupg
    else
        # EPEL provides certbot on RHEL-family
        dnf install -y epel-release
        dnf install -y nginx certbot python3-certbot-nginx \
            git curl unzip rsync ca-certificates
        # Allow nginx to proxy to localhost (SELinux)
        setsebool -P httpd_can_network_connect 1 2>/dev/null || \
            warn "SELinux: could not set httpd_can_network_connect — set manually if proxying fails"
    fi

    # Open firewall ports if firewalld is active
    if command -v firewall-cmd &>/dev/null && systemctl is-active --quiet firewalld 2>/dev/null; then
        firewall-cmd --permanent --add-service=http --add-service=https &>/dev/null
        firewall-cmd --reload &>/dev/null
        success "Firewall: HTTP and HTTPS opened"
    fi

    systemctl enable nginx
    systemctl start  nginx
    success "Base packages installed — nginx $(nginx -v 2>&1 | grep -oP '[\d.]+')"
}

install_nodejs() {
    local MIN=18 VER=20
    if command -v node &>/dev/null; then
        local cur
        cur=$(node -e 'process.stdout.write(process.version.slice(1).split(".")[0])' 2>/dev/null || echo 0)
        if [[ "$cur" -ge "$MIN" ]]; then
            info "Node.js $(node -v) already installed — skipping"
            return 0
        fi
        info "Node.js $cur < $MIN — upgrading to $VER…"
    fi

    local setup_url
    if [[ "$OS_FAMILY" == "debian" ]]; then
        setup_url="https://deb.nodesource.com/setup_${VER}.x"
    else
        setup_url="https://rpm.nodesource.com/setup_${VER}.x"
    fi

    curl -fsSL "$setup_url" | bash - || die "NodeSource setup failed"

    if [[ "$OS_FAMILY" == "debian" ]]; then
        apt-get install -y nodejs
    else
        dnf install -y nodejs
    fi
    success "Node.js $(node -v) installed"
}

# ─── Repo & frontend ──────────────────────────────────────────────────────────
pull_repo() {
    section "Pulling Office Tools from GitHub"
    if [[ -d "$REPO_DIR/.git" ]]; then
        info "Repo found — fetching latest…"
        git -C "$REPO_DIR" fetch origin
        local branch
        branch=$(git -C "$REPO_DIR" branch --show-current 2>/dev/null || echo "master")
        git -C "$REPO_DIR" reset --hard "origin/$branch"
    else
        info "Cloning $REPO_URL…"
        mkdir -p "$(dirname "$REPO_DIR")"
        git clone "$REPO_URL" "$REPO_DIR"
    fi
    success "Repo: $(git -C "$REPO_DIR" log -1 --format='%h %s')"
}

sync_frontend() {
    local domain="${1:-}"
    section "Syncing frontend → $WEB_ROOT"
    mkdir -p "$WEB_ROOT"
    rsync -a --delete \
        --exclude='.git' \
        --exclude='.gitignore' \
        --exclude='backend' \
        --exclude='deploy.sh' \
        --exclude='undeploy.sh' \
        --exclude='*.md' \
        "$REPO_DIR/" "$WEB_ROOT/"
    chown -R www-data:www-data "$WEB_ROOT"
    chmod -R 755 "$WEB_ROOT"
    find "$WEB_ROOT" -type f -exec chmod 644 {} \;

    if [[ "$OS_FAMILY" == "rhel" ]]; then
        chcon -R -t httpd_sys_content_t "$WEB_ROOT" 2>/dev/null || true
    fi

    [[ -n "$domain" ]] && _patch_domain "$REPO_DIR" "$domain"
    [[ -n "$domain" ]] && _patch_domain "$WEB_ROOT"  "$domain"

    success "Frontend deployed to $WEB_ROOT"
}

_patch_domain() {
    local dir="$1" domain="$2"
    local cfg="$dir/js/config.js"
    if [[ -f "$cfg" ]]; then
        sed -i "s|https://pb\.yourdomain\.com|https://${domain}/pb-api|g"  "$cfg"
        sed -i "s|https://pay\.yourdomain\.com|https://${domain}/pay-api|g" "$cfg"
        sed -i "s|https://yourdomain\.com|https://${domain}|g"              "$cfg"
    fi
    find "$dir" -name "*.html" -not -path "*/.git/*" \
        -exec sed -i "s|https://yourdomain\.com|https://${domain}|g" {} \;
}

# ─── nginx config writers ──────────────────────────────────────────────────────
_nginx_enable() {
    if [[ "$OS_FAMILY" == "debian" ]]; then
        ln -sf "$NGINX_CONF_PATH" "$NGINX_ENABLED_PATH"
        rm -f /etc/nginx/sites-enabled/default
    fi
    nginx -t 2>&1 || die "nginx config test failed — check $NGINX_CONF_PATH"
    systemctl reload nginx
}

write_nginx_http() {
    local domain="$1"
    cat > "$NGINX_CONF_PATH" << NGINXEOF
# Office Tools — managed by deploy.sh (HTTP — certbot will add SSL)
server {
    listen 80;
    listen [::]:80;
    server_name ${domain};

    root  ${WEB_ROOT};
    index index.html;

    location / { try_files \$uri \$uri/ \$uri.html =404; }

    location ^~ /pb-api/ {
        proxy_pass         http://127.0.0.1:8090/;
        proxy_http_version 1.1;
        proxy_set_header   Upgrade           \$http_upgrade;
        proxy_set_header   Connection        "upgrade";
        proxy_set_header   Host              \$host;
        proxy_set_header   X-Real-IP         \$remote_addr;
        proxy_set_header   X-Forwarded-For   \$proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto \$scheme;
        proxy_read_timeout 300s;
        proxy_buffering    off;
    }
    location ^~ /pay-api/ {
        proxy_pass         http://127.0.0.1:3001/;
        proxy_http_version 1.1;
        proxy_set_header   Host              \$host;
        proxy_set_header   X-Real-IP         \$remote_addr;
        proxy_set_header   X-Forwarded-For   \$proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto \$scheme;
    }
    location ~ /\.                           { deny all; return 404; }
    location /backend/                       { deny all; return 404; }
    location ~ \.(env|sh|json|md|toml|log)$ { deny all; return 404; }
}
NGINXEOF
    _nginx_enable
    success "nginx HTTP config written for ${domain}"
}

write_nginx_https() {
    local domain="$1"
    local ssl_cert="/etc/letsencrypt/live/${domain}/fullchain.pem"
    local ssl_key="/etc/letsencrypt/live/${domain}/privkey.pem"

    cat > "$NGINX_CONF_PATH" << NGINXEOF
# Office Tools — managed by deploy.sh

server {
    listen 80;
    listen [::]:80;
    server_name ${domain};
    return 301 https://\$host\$request_uri;
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name ${domain};

    ssl_certificate     ${ssl_cert};
    ssl_certificate_key ${ssl_key};
    ssl_protocols             TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers on;
    ssl_ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305;
    ssl_session_cache   shared:SSL:10m;
    ssl_session_timeout 1d;
    ssl_session_tickets off;

    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;
    add_header X-Frame-Options           "SAMEORIGIN"             always;
    add_header X-Content-Type-Options    "nosniff"                always;
    add_header X-XSS-Protection          "1; mode=block"          always;
    add_header Referrer-Policy           "strict-origin-when-cross-origin" always;
    add_header Permissions-Policy        "camera=(), microphone=(), geolocation=()" always;

    gzip on; gzip_vary on;
    gzip_types text/plain text/css text/javascript application/javascript application/json image/svg+xml;
    gzip_min_length 1024;

    client_max_body_size 1100M;

    root  ${WEB_ROOT};
    index index.html;

    location / { try_files \$uri \$uri/ \$uri.html =404; }

    location ~* \.(css|js|png|jpg|jpeg|gif|ico|svg|woff2|woff)$ {
        expires 7d;
        add_header Cache-Control "public, immutable";
    }

    location ^~ /pb-api/ {
        proxy_pass         http://127.0.0.1:8090/;
        proxy_http_version 1.1;
        proxy_set_header   Upgrade           \$http_upgrade;
        proxy_set_header   Connection        "upgrade";
        proxy_set_header   Host              \$host;
        proxy_set_header   X-Real-IP         \$remote_addr;
        proxy_set_header   X-Forwarded-For   \$proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto \$scheme;
        proxy_read_timeout 300s;
        proxy_buffering    off;
        client_max_body_size 1100M;
    }
    location ^~ /_/ {
        proxy_pass http://127.0.0.1:8090/_/;
        proxy_http_version 1.1;
        proxy_set_header Host              \$host;
        proxy_set_header X-Real-IP         \$remote_addr;
        proxy_set_header X-Forwarded-For   \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
    }
    location ^~ /api/ {
        proxy_pass http://127.0.0.1:8090/api/;
        proxy_http_version 1.1;
        proxy_set_header Host              \$host;
        proxy_set_header X-Real-IP         \$remote_addr;
        proxy_set_header X-Forwarded-For   \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
    }
    location ^~ /pay-api/ {
        proxy_pass         http://127.0.0.1:3001/;
        proxy_http_version 1.1;
        proxy_set_header   Host              \$host;
        proxy_set_header   X-Real-IP         \$remote_addr;
        proxy_set_header   X-Forwarded-For   \$proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto \$scheme;
        proxy_read_timeout 60s;
    }

    location ~ /\.                           { deny all; return 404; }
    location /backend/                       { deny all; return 404; }
    location ~ \.(env|sh|json|md|toml|log)$ { deny all; return 404; }
}
NGINXEOF
    _nginx_enable
    success "nginx HTTPS config hardened for ${domain}"
}

get_ssl() {
    local domain="$1" email="$2"
    section "Getting Let's Encrypt SSL for ${domain}"
    echo -e "  ${YELLOW}${BOLD}[!] Cloudflare users:${RESET} ${YELLOW}If your domain uses Cloudflare,${RESET}"
    echo -e "  ${YELLOW}    set the DNS record to ${BOLD}DNS only${RESET}${YELLOW} (grey cloud) before continuing.${RESET}"
    echo -e "  ${YELLOW}    Leaving it on ${BOLD}Proxied${RESET}${YELLOW} (orange cloud) will cause certificate${RESET}"
    echo -e "  ${YELLOW}    generation to fail. You can re-enable proxying after SSL is issued.${RESET}"
    echo ""
    certbot --nginx -d "$domain" \
        --non-interactive --agree-tos \
        -m "$email" --redirect
    success "SSL certificate issued"
}

# ─── Backend ──────────────────────────────────────────────────────────────────
setup_backend_first() {
    local domain="$1"

    section "Backend setup — PocketBase + Grin payment server"
    echo -ne "  PocketBase admin email:    "; read -r PB_ADMIN_EMAIL
    echo -ne "  PocketBase admin password: "; read -rs _PB_PASS; echo ""
    echo -ne "  Grin wallet password:      "; read -rs _GW_PASS; echo ""
    echo ""
    info "Get your Grin receiving address with: grin-wallet address"
    echo -ne "  Grin receiving address (Enter to skip): "; read -r _GW_ADDR

    mkdir -p "$BACKEND_DIR"
    rsync -a "$REPO_DIR/backend/" "$BACKEND_DIR/"

    cat > "$BACKEND_DIR/.env" << ENVEOF
# Office Tools backend config
GRIN_WALLET_PASS=${_GW_PASS}
GRIN_RECEIVING_ADDRESS=${_GW_ADDR}
PB_URL=http://127.0.0.1:8090
PB_ADMIN_EMAIL=${PB_ADMIN_EMAIL}
PB_ADMIN_PASSWORD=${_PB_PASS}
PORT=3001
CORS_ORIGINS=https://${domain}
PAYMENT_EXPIRY_MINUTES=30
PLAN_PRO_MONTHLY_NANOGRIN=10000000000
PLAN_PRO_YEARLY_NANOGRIN=100000000000
PLAN_LIFETIME_NANOGRIN=500000000000
ENVEOF
    chmod 600 "$BACKEND_DIR/.env"

    cd "$BACKEND_DIR" && npm install --omit=dev && cd /
    success "Backend files ready at $BACKEND_DIR"

    # Download PocketBase
    section "Downloading PocketBase"
    mkdir -p "$PB_DIR"
    local pb_ver
    pb_ver=$(curl -s https://api.github.com/repos/pocketbase/pocketbase/releases/latest \
        | grep '"tag_name"' | cut -d'"' -f4 | sed 's/v//')
    local pb_zip="pocketbase_${pb_ver}_linux_amd64.zip"
    curl -L "https://github.com/pocketbase/pocketbase/releases/download/v${pb_ver}/${pb_zip}" \
        -o "/tmp/${pb_zip}"
    unzip -o "/tmp/${pb_zip}" -d "$PB_DIR"
    chmod +x "$PB_DIR/pocketbase"
    rm -f "/tmp/${pb_zip}"
    mkdir -p "$PB_DIR/pb_hooks"
    cp "$BACKEND_DIR/pb_hooks/main.pb.js" "$PB_DIR/pb_hooks/"
    chown -R www-data:www-data "$PB_DIR"
    success "PocketBase ${pb_ver} installed at $PB_DIR"

    # Systemd services
    section "Creating systemd services"
    cat > /etc/systemd/system/office-tools-pb.service << PBEOF
[Unit]
Description=Office Tools — PocketBase
After=network.target
[Service]
Type=simple
User=www-data
Group=www-data
WorkingDirectory=${PB_DIR}
ExecStart=${PB_DIR}/pocketbase serve --http=127.0.0.1:8090
Restart=on-failure
RestartSec=5s
StandardOutput=journal
StandardError=journal
[Install]
WantedBy=multi-user.target
PBEOF

    cat > /etc/systemd/system/office-tools-pay.service << PAYEOF
[Unit]
Description=Office Tools — Grin Payment Server
After=network.target office-tools-pb.service
[Service]
Type=simple
User=www-data
Group=www-data
WorkingDirectory=${BACKEND_DIR}
ExecStart=/usr/bin/node grin-payment-server.js
EnvironmentFile=${BACKEND_DIR}/.env
Restart=on-failure
RestartSec=5s
StandardOutput=journal
StandardError=journal
[Install]
WantedBy=multi-user.target
PAYEOF

    systemctl daemon-reload
    systemctl enable office-tools-pb office-tools-pay
    systemctl start  office-tools-pb

    info "Waiting for PocketBase to initialize…"
    local _waited=0
    while ! curl -s "http://127.0.0.1:8090/api/health" | grep -q '"code":200' 2>/dev/null; do
        sleep 2; _waited=$((_waited+2))
        [[ $_waited -ge 30 ]] && { warn "PocketBase did not respond in 30 s"; break; }
    done

    if [[ -n "$PB_ADMIN_EMAIL" && -n "$_PB_PASS" ]]; then
        "$PB_DIR/pocketbase" superuser upsert "$PB_ADMIN_EMAIL" "$_PB_PASS" \
            && success "PocketBase superuser created: $PB_ADMIN_EMAIL" \
            || warn "Superuser creation failed — use Option 4 to retry"
        setup_pb_collections "$PB_ADMIN_EMAIL" "$_PB_PASS"
    fi

    systemctl start office-tools-pay || \
        warn "Payment server failed to start — check: journalctl -u office-tools-pay"

    success "Backend services enabled and started"
}

# ─── PocketBase collection auto-setup ─────────────────────────────────────────
# Creates short_urls, pastes, shared_files collections via PocketBase API.
# Requires Node.js (installed in Option 1). Safe to call multiple times.
setup_pb_collections() {
    local email="$1" pass="$2"
    section "Setting up PocketBase collections"

    if ! command -v node &>/dev/null; then
        warn "Node.js not found — skipping collection setup. Run Option 1 first."
        return 1
    fi

    # Write temp Node.js script
    local tmp="/tmp/_pb_init_collections.js"
    cat > "$tmp" << 'NODESCRIPT'
const http = require('http');
const email = process.env.PB_EMAIL;
const pass  = process.env.PB_PASS;

function req(method, path, body, token) {
  return new Promise((res, rej) => {
    const data = body ? JSON.stringify(body) : null;
    const hdrs = { 'Content-Type': 'application/json' };
    if (token) hdrs['Authorization'] = 'Bearer ' + token;
    if (data)  hdrs['Content-Length'] = Buffer.byteLength(data);
    const r = http.request({ hostname:'127.0.0.1', port:8090, path, method, headers:hdrs }, rsp => {
      let d = '';
      rsp.on('data', c => d += c);
      rsp.on('end', () => { try { res({ status: rsp.statusCode, body: JSON.parse(d) }); } catch { res({ status: rsp.statusCode, body: d }); } });
    });
    r.on('error', rej);
    if (data) r.write(data);
    r.end();
  });
}

// Public access rules: anyone can list/view/create; only admin can update/delete
const PUBLIC_RULES = { listRule: '', viewRule: '', createRule: '', updateRule: null, deleteRule: null };

const COLLECTIONS = [
  { name: 'short_urls', type: 'base', ...PUBLIC_RULES, fields: [
      { name: 'code',     type: 'text', required: true  },
      { name: 'long_url', type: 'text', required: true  },
      { name: 'expires',  type: 'date', required: false }
  ]},
  { name: 'pastes', type: 'base', ...PUBLIC_RULES, fields: [
      { name: 'code',            type: 'text', required: true  },
      { name: 'title',           type: 'text', required: false },
      { name: 'content',         type: 'text', required: true  },
      { name: 'syntax',          type: 'text', required: false },
      { name: 'expires',         type: 'date', required: false },
      { name: 'burn_after_read', type: 'bool', required: false }
  ]},
  { name: 'file_shares', type: 'base', ...PUBLIC_RULES, fields: [
      { name: 'code',          type: 'text', required: true  },
      { name: 'original_name', type: 'text', required: false },
      { name: 'file_size',     type: 'number', required: false },
      { name: 'file',          type: 'file', required: true,
        options: { maxSize: 1073741824, maxSelect: 1 }   },
      { name: 'expires',       type: 'date', required: false }
  ]},
];

async function main() {
  // Authenticate — try new API (PB 0.23+) then fall back to old
  let token = null;
  const authPaths = ['/api/superusers/auth-with-password', '/api/admins/auth-with-password'];
  for (const path of authPaths) {
    try {
      const r = await req('POST', path, { identity: email, password: pass });
      console.log('  Auth ' + path + ' → HTTP ' + r.status);
      if (r.body && r.body.token) { token = r.body.token; break; }
      if (r.status !== 404) console.error('  Auth error: ' + JSON.stringify(r.body));
    } catch(e) { console.error('  Auth exception on ' + path + ': ' + e.message); }
  }
  if (!token) { console.error('AUTH_FAILED: could not authenticate with PocketBase'); process.exit(1); }
  console.log('  Authenticated with PocketBase');

  for (const col of COLLECTIONS) {
    const { fields, ...meta } = col;
    const check = await req('GET', '/api/collections/' + col.name, null, token);
    if (check.status === 200) {
      // Patch rules on existing collection to ensure public access
      await req('PATCH', '/api/collections/' + col.name, PUBLIC_RULES, token);
      console.log('  EXISTS:   ' + col.name + ' (rules synced)');
      continue;
    }
    const r = await req('POST', '/api/collections', { ...meta, fields }, token);
    if (r.body && r.body.name) console.log('  CREATED:  ' + col.name);
    else console.error('  FAILED:   ' + col.name + ' — ' + (r.body && r.body.message || JSON.stringify(r.body)));
  }
}
main().catch(e => { console.error('ERROR: ' + e.message); process.exit(1); });
NODESCRIPT

    PB_EMAIL="$email" PB_PASS="$pass" node "$tmp" \
        && success "PocketBase collections ready" \
        || warn "Some collections may need manual creation — visit https://${DOMAIN}/_/"
    rm -f "$tmp"
}

sync_backend() {
    section "Syncing backend files"
    rsync -a --exclude='.env' "$REPO_DIR/backend/" "$BACKEND_DIR/"
    cd "$BACKEND_DIR" && npm install --omit=dev && cd /
    cp "$BACKEND_DIR/pb_hooks/main.pb.js" "$PB_DIR/pb_hooks/" 2>/dev/null || true
    systemctl restart office-tools-pb office-tools-pay 2>/dev/null || true
    success "Backend synced and services restarted"
}

# ─── Summary printer ──────────────────────────────────────────────────────────
print_summary() {
    local domain="$1"
    echo ""
    echo -e "${BOLD}${GREEN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${RESET}"
    echo -e "${BOLD}${GREEN}  ✔  https://${domain}  is live${RESET}"
    echo -e "${BOLD}${GREEN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${RESET}"
    echo ""
    echo -e "  ${BOLD}Site:${RESET}           https://${domain}/"
    echo -e "  ${BOLD}PocketBase UI:${RESET}  https://${domain}/_/"
    echo -e "  ${BOLD}PB API:${RESET}         https://${domain}/pb-api/"
    echo -e "  ${BOLD}Web root:${RESET}       ${WEB_ROOT}"
    echo -e "  ${BOLD}nginx config:${RESET}   ${NGINX_CONF_PATH}"
    echo -e "  ${BOLD}Repo:${RESET}           ${REPO_DIR}"
    echo -e "  ${BOLD}Logs:${RESET}           ${LOG_DIR}/"
    echo ""
}

# ─── Banner & status ──────────────────────────────────────────────────────────
show_banner() {
    clear
    echo ""
    echo -e "${BOLD}${CYAN}╔═══════════════════════════════════════════════════════╗${RESET}"
    echo -e "${BOLD}${CYAN}║       Office Tools — Deploy Manager                   ║${RESET}"
    echo -e "${BOLD}${CYAN}║       github.com/noobvie/Office_Tools                 ║${RESET}"
    echo -e "${BOLD}${CYAN}╚═══════════════════════════════════════════════════════╝${RESET}"
    echo ""
    echo -e "  ${DIM}OS: ${OS_NAME}${RESET}"
}

show_status() {
    load_conf
    echo -e "  ${BOLD}Current status${RESET}"
    echo -e "  ──────────────────────────────────────────────────"

    if [[ -n "$DOMAIN" ]]; then
        echo -e "  ${GREEN}●${RESET} Domain     : ${BOLD}${DOMAIN}${RESET}"
    else
        echo -e "  ${DIM}○ Domain     : not configured${RESET}"
    fi

    if [[ -d "$REPO_DIR/.git" ]]; then
        local commit; commit=$(git -C "$REPO_DIR" log -1 --format='%h %s' 2>/dev/null || echo "unknown")
        echo -e "  ${GREEN}●${RESET} Repo       : ${DIM}${commit}${RESET}"
    else
        echo -e "  ${DIM}○ Repo       : not cloned${RESET}"
    fi

    local svcs=("nginx" "office-tools-pb" "office-tools-pay")
    for svc in "${svcs[@]}"; do
        if systemctl is-active --quiet "$svc" 2>/dev/null; then
            echo -e "  ${GREEN}●${RESET} ${svc}  ${DIM}running${RESET}"
        elif systemctl list-unit-files "${svc}.service" &>/dev/null 2>&1 \
             && systemctl list-unit-files "${svc}.service" 2>/dev/null | grep -q "${svc}"; then
            echo -e "  ${YELLOW}●${RESET} ${svc}  ${DIM}stopped${RESET}"
        fi
    done
    echo ""
}

# ─── Option 1: Install / Update ───────────────────────────────────────────────
opt_1_install_update() {
    show_banner
    section "Option 1 — Install / Update"

    echo -e "  This will:"
    echo -e "    ${CYAN}·${RESET} Update OS packages   ${DIM}(${OS_FAMILY})${RESET}"
    echo -e "    ${CYAN}·${RESET} Install / update:    nginx · certbot · Node.js · git · curl"
    echo -e "    ${CYAN}·${RESET} Pull latest code     ${DIM}(Office Tools GitHub)${RESET}"
    echo -e "    ${CYAN}·${RESET} Sync frontend files  ${DIM}→ $WEB_ROOT${RESET}"
    echo -e "    ${CYAN}·${RESET} Restart services     ${DIM}(if already configured)${RESET}"
    echo ""
    ask_proceed "Proceed" || return 0

    mkdir -p "$LOG_DIR"
    local logf="$LOG_DIR/install_$(date +%Y%m%d_%H%M%S).log"
    info "Logging to: $logf"

    (
        set -euo pipefail
        exec > >(tee "$logf") 2>&1
        pkg_update_os
        install_base_packages
        install_nodejs
        pull_repo
        load_conf
        sync_frontend "${DOMAIN:-}"
        if [[ -n "$DOMAIN" ]]; then
            [[ -d "$BACKEND_DIR" ]] && sync_backend || true
            systemctl reload nginx 2>/dev/null || true
        fi
    ) || warn "Some steps had errors — check $logf"

    load_conf
    if [[ -n "$DOMAIN" ]]; then
        success "Update complete — https://${DOMAIN}"
    else
        success "Packages installed. Run Option 2 to configure a domain."
    fi

    press_enter
}

# ─── Option 2: Add / Configure Domain ─────────────────────────────────────────
opt_2_add_domain() {
    show_banner
    section "Option 2 — Add / Configure Domain"

    load_conf

    # Prerequisites check
    if ! command -v nginx &>/dev/null; then
        warn "nginx not installed. Run Option 1 first."
        press_enter; return 0
    fi
    if ! command -v certbot &>/dev/null; then
        warn "certbot not installed. Run Option 1 first."
        press_enter; return 0
    fi
    if [[ ! -d "$REPO_DIR/.git" ]]; then
        warn "Repository not cloned. Run Option 1 first."
        press_enter; return 0
    fi

    # Domain prompt
    echo ""
    [[ -n "$DOMAIN" ]] && echo -e "  ${DIM}Current domain: ${DOMAIN}${RESET}"
    echo -e "  ${DIM}(enter 0 at any prompt to cancel and return to menu)${RESET}"
    while true; do
        local _prompt="  ${BOLD}Domain name${RESET}"
        [[ -n "$DOMAIN" ]] && _prompt+=" (Enter = keep ${DIM}[$DOMAIN]${RESET})"
        _prompt+=": "
        echo -ne "$_prompt"
        read -r _new
        [[ "$_new" == "0" ]] && return 0
        if [[ -n "$_new" ]]; then DOMAIN="$_new"; break
        elif [[ -n "$DOMAIN" ]]; then break
        else warn "Domain cannot be empty."; fi
    done

    # Email prompt
    while true; do
        local _eprompt="  ${BOLD}Email for SSL${RESET}"
        [[ -n "$EMAIL" ]] && _eprompt+=" (Enter = keep ${DIM}[$EMAIL]${RESET})"
        _eprompt+=": "
        echo -ne "$_eprompt"
        read -r _new
        [[ "$_new" == "0" ]] && return 0
        if [[ -n "$_new" ]]; then EMAIL="$_new"; break
        elif [[ -n "$EMAIL" ]]; then break
        else warn "Email cannot be empty."; fi
    done

    # Backend — only prompt on first install
    local _do_backend=false
    if [[ ! -x "$PB_DIR/pocketbase" ]]; then
        echo ""
        echo -e "  ${DIM}Backend services (PocketBase + Grin payment server) are optional.${RESET}"
        echo -ne "  Set up backend? [Y/n]: "
        read -r _b; _b="${_b:-Y}"
        [[ "${_b,,}" == "y" ]] && _do_backend=true && SETUP_BACKEND="y"
    else
        info "Backend already installed — will sync files only"
    fi

    echo ""
    echo -e "  Domain   : ${BOLD}${DOMAIN}${RESET}"
    echo -e "  Email    : ${DOMAIN:+$EMAIL}"
    echo -e "  Web root : $WEB_ROOT"
    echo ""
    ask_proceed "Proceed" || return 0

    mkdir -p "$LOG_DIR"
    local logf="$LOG_DIR/domain_$(date +%Y%m%d_%H%M%S).log"
    info "Logging to: $logf"

    (
        set -euo pipefail
        exec > >(tee "$logf") 2>&1

        sync_frontend "$DOMAIN"
        write_nginx_http "$DOMAIN"
        get_ssl "$DOMAIN" "$EMAIL"
        write_nginx_https "$DOMAIN"

        if [[ "$_do_backend" == true ]]; then
            setup_backend_first "$DOMAIN"
        elif [[ -d "$BACKEND_DIR" ]]; then
            sync_backend
        fi
    ) || { warn "Errors during setup — check $logf"; press_enter; return 0; }

    save_conf
    print_summary "$DOMAIN"
    press_enter
}

# ─── Option 3: Remove / Switch Domain ─────────────────────────────────────────
opt_3_remove_switch() {
    show_banner
    section "Option 3 — Remove / Switch Domain"

    load_conf

    if [[ -z "$DOMAIN" ]]; then
        warn "No domain configured. Nothing to remove or switch."
        press_enter; return 0
    fi

    echo -e "  Configured domain: ${BOLD}${DOMAIN}${RESET}"
    echo ""
    echo -e "    ${YELLOW}a)${RESET}  Remove domain         ${DIM}nginx config + SSL cert only — files kept${RESET}"
    echo -e "    ${YELLOW}b)${RESET}  Switch to new domain  ${DIM}remove old config, set up new domain + SSL${RESET}"
    echo -e "    ${YELLOW}0)${RESET}  Back"
    echo ""
    echo -ne "  Choose [a/b/0]: "; read -r _sub

    case "${_sub,,}" in
      a)
        echo ""
        echo -ne "  ${BOLD}${YELLOW}Type 'yes' to confirm removing config for ${DOMAIN}: ${RESET}"
        read -r _c
        [[ "$_c" != "yes" ]] && info "Aborted."; [[ "$_c" != "yes" ]] && press_enter && return 0

        # Remove nginx config
        if [[ -e "$NGINX_CONF_PATH" ]]; then
            rm -f "$NGINX_CONF_PATH"
            success "Removed: $NGINX_CONF_PATH"
        fi
        if [[ -n "$NGINX_ENABLED_PATH" && -L "$NGINX_ENABLED_PATH" ]]; then
            rm -f "$NGINX_ENABLED_PATH"
            success "Removed symlink: $NGINX_ENABLED_PATH"
        fi
        if nginx -t 2>/dev/null; then
            systemctl reload nginx
            success "nginx reloaded"
        else
            warn "nginx config test failed — check /etc/nginx/ manually"
        fi

        # Remove SSL cert
        if [[ -d "/etc/letsencrypt/live/${DOMAIN}" ]]; then
            certbot delete --cert-name "$DOMAIN" --non-interactive 2>/dev/null || {
                rm -rf "/etc/letsencrypt/live/${DOMAIN}"
                rm -f  "/etc/letsencrypt/renewal/${DOMAIN}.conf"
            }
            success "SSL certificate removed for $DOMAIN"
        fi

        local _old="$DOMAIN"
        DOMAIN=""
        save_conf
        success "Domain '$_old' removed. Use Option 2 to configure a new domain."
        ;;

      b)
        echo ""
        while true; do
            echo -ne "  ${BOLD}New domain name${RESET}: "
            read -r _new
            [[ -n "$_new" ]] && break
            warn "Domain cannot be empty."
        done
        echo -ne "  ${BOLD}Email for SSL${RESET} (Enter = keep [$EMAIL]): "
        read -r _em; [[ -n "$_em" ]] && EMAIL="$_em"

        echo ""
        echo -e "  Will remove: ${BOLD}${DOMAIN}${RESET}"
        echo -e "  Will set up: ${BOLD}${_new}${RESET}"
        echo ""
        ask_proceed "Proceed" || return 0

        mkdir -p "$LOG_DIR"
        local logf="$LOG_DIR/switch_$(date +%Y%m%d_%H%M%S).log"

        (
            set -euo pipefail
            exec > >(tee "$logf") 2>&1

            section "Removing old domain: $DOMAIN"
            rm -f "$NGINX_CONF_PATH" 2>/dev/null || true
            [[ -n "$NGINX_ENABLED_PATH" ]] && rm -f "$NGINX_ENABLED_PATH" 2>/dev/null || true
            certbot delete --cert-name "$DOMAIN" --non-interactive 2>/dev/null || true
            nginx -t 2>/dev/null && systemctl reload nginx || true
            success "Old domain removed"

            DOMAIN="$_new"

            section "Setting up new domain: $DOMAIN"
            sync_frontend "$DOMAIN"
            write_nginx_http "$DOMAIN"
            get_ssl "$DOMAIN" "$EMAIL"
            write_nginx_https "$DOMAIN"
            [[ -d "$BACKEND_DIR" ]] && sync_backend || true
        ) || { warn "Errors during switch — check $logf"; press_enter; return 0; }

        DOMAIN="$_new"
        save_conf
        print_summary "$DOMAIN"
        ;;

      *) info "Back to main menu." ;;
    esac

    press_enter
}

# ─── Option 4: Set / Reset Admin Account ─────────────────────────────────────
opt_4_set_admin() {
    show_banner
    section "Option 4 — Set / Reset Admin Account"

    if [[ ! -x "$PB_DIR/pocketbase" ]]; then
        warn "PocketBase is not installed. Run Option 2 to set up the backend first."
        press_enter; return 0
    fi

    echo ""
    echo -e "  Use this option to create or reset the PocketBase admin account."
    echo -e "  The admin UI is accessible at: ${BOLD}https://${DOMAIN:-<your-domain>}/_/${RESET}"
    echo ""
    echo -ne "  Admin email (0 to cancel): "; read -r _email
    [[ "$_email" == "0" || -z "$_email" ]] && return 0

    echo -ne "  New password (min 8 chars): "; read -rs _pass; echo ""
    [[ "$_pass" == "0" || -z "$_pass" ]] && return 0
    if [[ ${#_pass} -lt 8 ]]; then
        warn "Password must be at least 8 characters."; press_enter; return 0
    fi
    echo -ne "  Confirm password:          "; read -rs _pass2; echo ""
    if [[ "$_pass" != "$_pass2" ]]; then
        warn "Passwords do not match."; press_enter; return 0
    fi

    # Ensure PocketBase is running
    if ! systemctl is-active --quiet office-tools-pb 2>/dev/null; then
        info "Starting PocketBase…"
        systemctl start office-tools-pb
        sleep 3
    fi

    "$PB_DIR/pocketbase" superuser upsert "$_email" "$_pass" \
        && success "Admin account set — you can now log in at https://${DOMAIN:-<domain>}/_/" \
        || { warn "Failed to update admin account."; press_enter; return 0; }

    # Update .env so payment server can authenticate
    if [[ -f "$BACKEND_DIR/.env" ]]; then
        sed -i "s|^PB_ADMIN_EMAIL=.*|PB_ADMIN_EMAIL=${_email}|"   "$BACKEND_DIR/.env"
        sed -i "s|^PB_ADMIN_PASSWORD=.*|PB_ADMIN_PASSWORD=${_pass}|" "$BACKEND_DIR/.env"
        systemctl restart office-tools-pay 2>/dev/null || true
        success ".env updated and payment server restarted"
    fi

    PB_ADMIN_EMAIL="$_email"
    save_conf

    # Offer to set Grin receiving address
    if [[ -f "$BACKEND_DIR/.env" ]]; then
        echo ""
        echo -ne "  Grin receiving address (Enter to skip): "; read -r _gaddr
        if [[ -n "$_gaddr" ]]; then
            if grep -q "^GRIN_RECEIVING_ADDRESS=" "$BACKEND_DIR/.env"; then
                sed -i "s|^GRIN_RECEIVING_ADDRESS=.*|GRIN_RECEIVING_ADDRESS=${_gaddr}|" "$BACKEND_DIR/.env"
            else
                echo "GRIN_RECEIVING_ADDRESS=${_gaddr}" >> "$BACKEND_DIR/.env"
            fi
            success "GRIN_RECEIVING_ADDRESS updated"
        fi
    fi

    # (Re-)create collections now that we have valid credentials
    setup_pb_collections "$_email" "$_pass"

    press_enter
}

# ─── Option 5: Update from Repo ───────────────────────────────────────────────
opt_5_update_repo() {
    show_banner
    section "Option 5 — Update from Repository"

    if [[ ! -d "$REPO_DIR/.git" ]]; then
        warn "Repository not cloned yet. Run Option 1 to install first."
        press_enter; return 0
    fi

    local current_branch
    current_branch=$(git -C "$REPO_DIR" branch --show-current 2>/dev/null || echo "unknown")

    echo -e "  Remote:         ${DIM}${REPO_URL}${RESET}"
    echo -e "  Current branch: ${BOLD}${current_branch}${RESET}"
    echo -e "  Last commit:    ${DIM}$(git -C "$REPO_DIR" log -1 --format='%h %s' 2>/dev/null)${RESET}"
    echo ""

    info "Fetching remote branch list…"
    git -C "$REPO_DIR" fetch --quiet origin 2>/dev/null \
        || warn "Could not reach remote — using cached branch list"

    local branches=()
    while IFS= read -r b; do
        [[ -z "$b" ]] && continue
        branches+=("$b")
    done < <(git -C "$REPO_DIR" branch -r 2>/dev/null \
        | grep -v '\->' | sed 's|[[:space:]]*origin/||')

    if [[ "${#branches[@]}" -gt 0 ]]; then
        echo -e "  ${BOLD}Available branches:${RESET}"
        local i=1
        for b in "${branches[@]}"; do
            local marker=""
            [[ "$b" == "$current_branch" ]] && marker=" ${DIM}← current${RESET}"
            printf "    %s%d)%s  %s%s\n" "${CYAN}" "$i" "${RESET}" "$b" "$marker"
            ((i++))
        done
        echo ""
    fi

    echo -ne "  Branch number or name (Enter = keep ${DIM}[${current_branch}]${RESET}, 0 to cancel): "
    read -r _input
    [[ "$_input" == "0" ]] && return 0

    local target_branch="$current_branch"
    if [[ -n "$_input" ]]; then
        if [[ "$_input" =~ ^[0-9]+$ ]] && (( _input >= 1 && _input <= ${#branches[@]} )); then
            target_branch="${branches[$(( _input - 1 ))]}"
        else
            target_branch="$_input"
        fi
    fi

    echo ""
    echo -e "  Target:  ${BOLD}${target_branch}${RESET}"
    ask_proceed "Proceed" || return 0

    mkdir -p "$LOG_DIR"
    local logf="$LOG_DIR/update_$(date +%Y%m%d_%H%M%S).log"
    info "Logging to: $logf"

    (
        set -euo pipefail
        exec > >(tee "$logf") 2>&1

        git -C "$REPO_DIR" fetch origin
        git -C "$REPO_DIR" checkout "$target_branch"
        git -C "$REPO_DIR" reset --hard "origin/$target_branch"
        success "Repo updated: $(git -C "$REPO_DIR" log -1 --format='%h %s')"

        load_conf
        sync_frontend "${DOMAIN:-}"

        # Sync backend if installed
        [[ -d "$BACKEND_DIR" ]] && sync_backend || true

        # Always reload nginx if it's running
        if systemctl is-active --quiet nginx 2>/dev/null; then
            systemctl reload nginx
            success "nginx reloaded"
        fi
    ) || { warn "Update failed — check $logf"; press_enter; return 0; }

    load_conf
    if [[ -n "$DOMAIN" ]]; then
        success "Updated to branch '${target_branch}' — https://${DOMAIN}"
    else
        success "Updated to branch '${target_branch}'"
    fi
    press_enter
}

# ─── DEL: Delete ──────────────────────────────────────────────────────────────
opt_del_delete() {
    show_banner
    section "Delete — Remove Office Tools"

    echo -e "  ${RED}${BOLD}This will PERMANENTLY remove Office Tools from this server.${RESET}"
    echo ""

    # Locate undeploy.sh
    local _undeploy=""
    for _p in \
        "$SCRIPT_DIR/undeploy.sh" \
        "$REPO_DIR/undeploy.sh" \
        "/opt/office-tools/repo/undeploy.sh"; do
        [[ -f "$_p" ]] && _undeploy="$_p" && break
    done

    if [[ -z "$_undeploy" ]]; then
        die "undeploy.sh not found. Copy it next to deploy.sh and retry."
    fi

    info "Will run: $_undeploy"
    echo ""
    bash "$_undeploy"
}

# ─── Main loop ────────────────────────────────────────────────────────────────
[[ "$EUID" -ne 0 ]] && die "Run as root: sudo bash deploy.sh"
detect_os

while true; do
    show_banner
    show_status

    echo -e "  ${BOLD}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${RESET}"
    echo -e "    ${BOLD}1)${RESET}   Install / Update    ${DIM}packages · OS · pull latest code${RESET}"
    echo -e "    ${BOLD}2)${RESET}   Add Domain          ${DIM}configure domain · SSL · backend${RESET}"
    echo -e "    ${BOLD}3)${RESET}   Remove / Switch     ${DIM}remove or change active domain${RESET}"
    echo -e "    ${BOLD}4)${RESET}   Set Admin Account   ${DIM}set/reset PocketBase admin credentials${RESET}"
    echo -e "    ${BOLD}5)${RESET}   Update from Repo    ${DIM}pull specific branch · restart services${RESET}"
    echo -e "  ${DIM}  ──────────────────────────────────────────────${RESET}"
    echo -e "  ${RED}  DEL)${RESET} Delete              ${DIM}permanently remove Office Tools${RESET}"
    echo -e "    ${BOLD}0)${RESET}   Exit"
    echo -e "  ${BOLD}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${RESET}"
    echo ""
    echo -ne "  Choose [0-5 / del]: "; read -r _choice
    echo ""

    case "${_choice,,}" in
        1)   opt_1_install_update ;;
        2)   opt_2_add_domain     ;;
        3)   opt_3_remove_switch  ;;
        4)   opt_4_set_admin      ;;
        5)   opt_5_update_repo    ;;
        del) opt_del_delete; break ;;
        0)   echo -e "${DIM}Goodbye.${RESET}"; exit 0 ;;
        *)   warn "Invalid choice: $_choice" ;;
    esac
done
