#!/bin/bash
# =============================================================================
# Office Tools — Deploy Manager
# Interactive menu for installation, domain management, and removal.
#
# Supports:  Debian · Ubuntu · AlmaLinux · Rocky Linux · CentOS Stream
# Usage:     sudo bash deploy.sh
# =============================================================================

# ─── Colors & helpers ─────────────────────────────────────────────────────────
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'
CYAN='\033[0;36m'; BOLD='\033[1m'; DIM='\033[2m'; RESET='\033[0m'

info()    { echo -e "${CYAN}[INFO]${RESET}  $*"; }
success() { echo -e "${GREEN}[OK]${RESET}    $*"; }
warn()    { echo -e "${YELLOW}[WARN]${RESET}  $*"; }
die()     { echo -e "${RED}${BOLD}[FATAL]${RESET} $*" >&2; exit 1; }

section() {
    echo ""
    echo -e "${BOLD}${CYAN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${RESET}"
    echo -e "${BOLD}${CYAN}  $*${RESET}"
    echo -e "${BOLD}${CYAN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${RESET}"
    echo ""
}

press_enter() {
    echo ""
    echo -ne "${DIM}  Press Enter to return to menu…${RESET}"
    read -r
}

# Returns 0 (true=proceed) or 1 (abort — n or 0 pressed)
ask_proceed() {
    local prompt="${1:-Proceed}"
    echo -ne "  ${BOLD}${prompt}? [Y/n/0]: ${RESET}"; read -r _ap
    [[ "${_ap,,}" == "n" || "$_ap" == "0" ]] && return 1
    return 0
}

# ─── Paths ────────────────────────────────────────────────────────────────────
REPO_URL="https://github.com/noobvie/Office_Tools.git"
REPO_DIR="/opt/office-tools/repo"
WEB_ROOT="/var/www/office-tools"
BACKEND_DIR="/opt/office-tools/backend"
YT_SERVER_DIR="/opt/office-tools/yt-server"
POT_SERVER_DIR="/opt/office-tools/pot-server"   # bgutil PO-token provider (YouTube bot-check bypass)
POT_PORT=4416
DEPLOY_CONF="/opt/office-tools/deploy.conf"
LOG_DIR="/var/log/office-tools"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# nginx config paths — set by detect_os()
NGINX_CONF_PATH=""
NGINX_ENABLED_PATH=""   # empty = not used (RHEL writes directly to conf.d)

# ─── OS detection ─────────────────────────────────────────────────────────────
OS_FAMILY=""   # "debian" or "rhel"
OS_NAME="unknown"

detect_os() {
    if [[ ! -f /etc/os-release ]]; then
        die "Cannot detect OS (/etc/os-release not found)."
    fi
    # shellcheck source=/dev/null
    source /etc/os-release
    OS_NAME="${PRETTY_NAME:-${NAME:-unknown}}"

    case "${ID:-}" in
        ubuntu|debian|linuxmint|pop)
            OS_FAMILY="debian" ;;
        almalinux|rocky|centos|rhel|fedora|ol)
            OS_FAMILY="rhel" ;;
        *)
            case "${ID_LIKE:-}" in
                *debian*) OS_FAMILY="debian" ;;
                *rhel*|*centos*|*fedora*) OS_FAMILY="rhel" ;;
                *) die "Unsupported OS: ${OS_NAME}. Use Debian/Ubuntu or AlmaLinux/Rocky Linux." ;;
            esac ;;
    esac

    if [[ "$OS_FAMILY" == "debian" ]]; then
        NGINX_CONF_PATH="/etc/nginx/sites-available/office-tools"
        NGINX_ENABLED_PATH="/etc/nginx/sites-enabled/office-tools"
    else
        NGINX_CONF_PATH="/etc/nginx/conf.d/office-tools.conf"
        NGINX_ENABLED_PATH=""
    fi
}

# ─── Config helpers ────────────────────────────────────────────────────────────
DOMAIN=""; EMAIL=""; SETUP_BACKEND="n"

load_conf() {
    DOMAIN=""; EMAIL=""; SETUP_BACKEND="n"
    [[ -f "$DEPLOY_CONF" ]] && source "$DEPLOY_CONF" || true
}

save_conf() {
    mkdir -p "$(dirname "$DEPLOY_CONF")"
    cat > "$DEPLOY_CONF" << CONFEOF
# Office Tools deploy config — auto-generated by deploy.sh
DOMAIN="${DOMAIN}"
EMAIL="${EMAIL}"
SETUP_BACKEND="${SETUP_BACKEND}"
CONFEOF
    chmod 600 "$DEPLOY_CONF"
}

# Idempotent "this key must exist in that .env" — creates the file when missing, adds
# the key only when absent, and never touches a value the operator already set.
# Used instead of a truncating `cat > .env`, which would silently drop operator
# settings (YTDLP_COOKIES above all) on every re-run of the installer.
env_ensure() {
    local file="$1" key="$2" val="$3"
    if [[ ! -f "$file" ]]; then
        install -m 600 /dev/null "$file" || return 1
    fi
    grep -qE "^[[:space:]]*${key}=" "$file" || printf '%s=%s\n' "$key" "$val" >> "$file"
}

# ─── System timezone ──────────────────────────────────────────────────────────
# Forces the server to UTC so logs and service timestamps are all consistent.
# Browser-based tools are unaffected by server timezone —
# they already use UTC JS methods internally.
enforce_utc_timezone() {
    section "Enforcing UTC system timezone"
    local current
    current=$(timedatectl show --property=Timezone --value 2>/dev/null \
              || cat /etc/timezone 2>/dev/null \
              || readlink /etc/localtime 2>/dev/null | sed 's|.*/zoneinfo/||' \
              || echo "unknown")

    if [[ "$current" == "UTC" ]]; then
        info "System timezone is already UTC — nothing to change."
        return 0
    fi

    warn "Current timezone: '${current}' — changing to UTC"
    if command -v timedatectl &>/dev/null; then
        timedatectl set-timezone UTC
    elif [[ -f /usr/share/zoneinfo/UTC ]]; then
        ln -sf /usr/share/zoneinfo/UTC /etc/localtime
        echo "UTC" > /etc/timezone
    else
        warn "Cannot set timezone automatically — set it manually: timedatectl set-timezone UTC"
        return 0
    fi

    success "Timezone set to UTC (was: ${current})"
    info "All server processes and logs will now use UTC timestamps."
}

# ─── Package management ────────────────────────────────────────────────────────
pkg_update_os() {
    section "Updating OS packages — ${OS_NAME}"
    if [[ "$OS_FAMILY" == "debian" ]]; then
        apt-get update -qq
        DEBIAN_FRONTEND=noninteractive apt-get upgrade -y
    else
        dnf upgrade -y --nobest 2>/dev/null || dnf upgrade -y
    fi
    success "OS packages updated"
}

pkg_install() {
    if [[ "$OS_FAMILY" == "debian" ]]; then
        apt-get install -y --no-install-recommends "$@"
    else
        dnf install -y "$@"
    fi
}

install_base_packages() {
    section "Installing base packages"
    if [[ "$OS_FAMILY" == "debian" ]]; then
        apt-get update -qq
        pkg_install nginx certbot python3-certbot-nginx \
            git curl unzip rsync ca-certificates gnupg python3-pip \
            iputils-ping traceroute
        # postfix — provides sendmail for feedback email notifications
        if ! command -v sendmail &>/dev/null; then
            echo "postfix postfix/mailname string $(hostname -f)"    | debconf-set-selections
            echo "postfix postfix/main_mailer_type string 'Internet Site'" | debconf-set-selections
            DEBIAN_FRONTEND=noninteractive pkg_install postfix
            systemctl enable postfix
            systemctl start  postfix
            success "postfix installed (sendmail provider)"
        else
            info "sendmail already available — skipping postfix install"
        fi
    else
        # EPEL provides certbot on RHEL-family
        dnf install -y epel-release
        dnf install -y nginx certbot python3-certbot-nginx \
            git curl unzip rsync ca-certificates python3-pip \
            iputils traceroute postfix
        systemctl enable postfix
        systemctl start  postfix
        # Allow nginx to proxy to localhost (SELinux)
        setsebool -P httpd_can_network_connect 1 2>/dev/null || \
            warn "SELinux: could not set httpd_can_network_connect — set manually if proxying fails"
    fi

    # Open firewall ports if firewalld is active
    if command -v firewall-cmd &>/dev/null && systemctl is-active --quiet firewalld 2>/dev/null; then
        firewall-cmd --permanent --add-service=http --add-service=https &>/dev/null
        firewall-cmd --reload &>/dev/null
        success "Firewall: HTTP and HTTPS opened"
    fi

    systemctl enable nginx
    systemctl start  nginx
    success "Base packages installed — nginx $(nginx -v 2>&1 | grep -oP '[\d.]+')"
}

install_nodejs() {
    # Node 26+ by choice. The hard requirement is only 24+ (the backend uses the
    # built-in node:sqlite module, unflagged from Node 24), but Office Tools is a
    # single-user deploy so we run the newer line for a more mature node:sqlite.
    # MIN = accept-as-is floor, VER = version installed when Node is missing/too old.
    # Note: 26 >= 24, so a box also running the mining pool (needs >=24) stays happy.
    local MIN=26 VER=26
    if command -v node &>/dev/null; then
        local cur
        cur=$(node -e 'process.stdout.write(process.version.slice(1).split(".")[0])' 2>/dev/null || echo 0)
        if [[ "$cur" -ge "$MIN" ]]; then
            info "Node.js $(node -v) already installed — skipping"
            return 0
        fi
        info "Node.js $cur < $MIN — upgrading to $VER…"
    fi

    local setup_url
    if [[ "$OS_FAMILY" == "debian" ]]; then
        setup_url="https://deb.nodesource.com/setup_${VER}.x"
    else
        setup_url="https://rpm.nodesource.com/setup_${VER}.x"
    fi

    curl -fsSL "$setup_url" | bash - || die "NodeSource setup failed"

    if [[ "$OS_FAMILY" == "debian" ]]; then
        apt-get install -y nodejs
    else
        dnf install -y nodejs
    fi
    success "Node.js $(node -v) installed"
}

# ─── ffmpeg ───────────────────────────────────────────────────────────────────
# Required by yt-dlp for MP3 conversion and 1080p video muxing.
install_ffmpeg() {
    section "Installing ffmpeg"

    if command -v ffmpeg &>/dev/null; then
        info "ffmpeg already installed: $(ffmpeg -version 2>&1 | head -1 | awk '{print $3}')"
        return 0
    fi

    info "Installing ffmpeg…"
    if [[ "$OS_FAMILY" == "debian" ]]; then
        pkg_install ffmpeg
    else
        # RHEL-family: ffmpeg lives in RPM Fusion (not in default repos).
        # EPEL is already installed by install_base_packages.
        local rhel_ver
        rhel_ver=$(rpm -E %rhel 2>/dev/null || echo 9)
        local rpm_fusion="https://download1.rpmfusion.org/free/el/rpmfusion-free-release-${rhel_ver}.noarch.rpm"
        dnf install -y "$rpm_fusion" 2>/dev/null \
            || warn "RPM Fusion install failed — trying dnf without it"
        dnf install -y ffmpeg 2>/dev/null \
            || warn "ffmpeg unavailable — video processing may be limited"
    fi
    command -v ffmpeg &>/dev/null \
        && success "ffmpeg installed: $(ffmpeg -version 2>&1 | head -1)" \
        || warn "ffmpeg not found — install manually if needed"
}

# ─── yt-dlp + PO-token plugin ─────────────────────────────────────────────────
# Required by yt-server for video/audio downloading.
# bgutil-ytdlp-pot-provider is the yt-dlp-sanctioned bot-check bypass: YouTube now
# requires PO (Proof of Origin) tokens on most player clients, and this plugin
# fetches them automatically from the local token server (see setup_pot_provider).
install_ytdlp() {
    section "Installing yt-dlp + PO-token plugin"

    if command -v yt-dlp &>/dev/null; then
        info "yt-dlp found — updating…"
    else
        info "Installing yt-dlp…"
    fi

    # --break-system-packages needed on Ubuntu 22.04+ / Debian 12+ (PEP 668)
    # bgutil plugin needs yt-dlp ≥ 2025.05.22 — always updating both together keeps that true.
    pip3 install -U yt-dlp bgutil-ytdlp-pot-provider --break-system-packages 2>/dev/null \
        || pip3 install -U yt-dlp bgutil-ytdlp-pot-provider \
        || { warn "yt-dlp install failed — YouTube downloads will not work"; return 0; }

    # Weekly auto-update cron — YouTube changes constantly; a stale yt-dlp or plugin is
    # the #1 cause of bot-check 403s. Always rewritten so old installs get the new steps.
    local cron_file="/etc/cron.weekly/yt-dlp-update"
    cat > "$cron_file" << 'CRONEOF'
#!/bin/bash
# Auto-generated by deploy.sh — keeps YouTube download stack current.
pip3 install -U yt-dlp bgutil-ytdlp-pot-provider --break-system-packages 2>/dev/null \
    || pip3 install -U yt-dlp bgutil-ytdlp-pot-provider
# Rebuild the PO-token provider server to match the plugin version (script written by deploy.sh)
[[ -x /opt/office-tools/pot-update.sh ]] && /opt/office-tools/pot-update.sh
systemctl restart office-tools-cobalt 2>/dev/null || true
CRONEOF
    chmod +x "$cron_file"
    success "Weekly auto-update cron installed (yt-dlp + PO-token plugin + provider)"

    command -v yt-dlp &>/dev/null \
        && success "yt-dlp installed: $(yt-dlp --version)" \
        || warn "yt-dlp not found — install manually: pip3 install yt-dlp"
}

# ─── PO-token provider server (bgutil) ────────────────────────────────────────
# Runs BotGuard locally and mints PO tokens on demand (port 4416). The pip plugin
# installed by install_ytdlp auto-detects it at http://127.0.0.1:4416 — no yt-dlp
# flags needed. Server checkout is pinned to the installed plugin's version tag
# (plugin and server must match per upstream docs).
setup_pot_provider() {
    section "Setting up PO-token provider (bgutil, port ${POT_PORT})"

    # Node ≥ 20 required by the provider (install_nodejs puts a current LTS in place)
    local node_major
    node_major=$(node -v 2>/dev/null | sed 's/^v//' | cut -d. -f1)
    if [[ -z "$node_major" || "$node_major" -lt 20 ]]; then
        warn "Node.js ≥ 20 required for the PO-token provider (found: $(node -v 2>/dev/null || echo none)) — skipping"
        return 0
    fi

    # Match the server checkout to the installed pip plugin version
    local pot_ver
    pot_ver=$(pip3 show bgutil-ytdlp-pot-provider 2>/dev/null | awk '/^Version:/{print $2}')
    if [[ -z "$pot_ver" ]]; then
        warn "bgutil-ytdlp-pot-provider pip plugin not installed — run install_ytdlp first; skipping"
        return 0
    fi

    if [[ -d "$POT_SERVER_DIR/.git" ]]; then
        info "Updating provider checkout to v${pot_ver}…"
        git -C "$POT_SERVER_DIR" fetch --tags -q origin \
            || warn "git fetch failed — building current checkout"
    else
        info "Cloning bgutil-ytdlp-pot-provider…"
        rm -rf "$POT_SERVER_DIR"
        git clone -q https://github.com/Brainicism/bgutil-ytdlp-pot-provider.git "$POT_SERVER_DIR" \
            || { warn "clone failed — PO-token provider not installed (YouTube may serve bot-check 403s)"; return 0; }
    fi
    git -C "$POT_SERVER_DIR" -c advice.detachedHead=false checkout -q "$pot_ver" 2>/dev/null \
        || warn "tag ${pot_ver} not found — building default branch instead"

    info "Building provider (npm ci + tsc)…"
    ( cd "$POT_SERVER_DIR/server" && npm ci --silent && npx tsc ) \
        || { warn "provider build failed — check npm/node output above"; return 0; }
    chown -R www-data:www-data "$POT_SERVER_DIR"

    # Standalone updater used by the weekly cron (keeps server matched to the pip plugin)
    cat > /opt/office-tools/pot-update.sh << POTUPEOF
#!/bin/bash
# Auto-generated by deploy.sh — sync PO-token provider server to the pip plugin version.
set -e
ver=\$(pip3 show bgutil-ytdlp-pot-provider 2>/dev/null | awk '/^Version:/{print \$2}')
[[ -n "\$ver" && -d "$POT_SERVER_DIR/.git" ]] || exit 0
cd "$POT_SERVER_DIR"
git fetch --tags -q origin || exit 0
git -c advice.detachedHead=false checkout -q "\$ver" || exit 0
cd server && npm ci --silent && npx tsc
chown -R www-data:www-data "$POT_SERVER_DIR"
systemctl restart office-tools-pot 2>/dev/null || true
POTUPEOF
    chmod +x /opt/office-tools/pot-update.sh

    # Systemd service — the provider has no bind-address option (listens on all
    # interfaces), so block external access at the firewall when ufw is active.
    cat > /etc/systemd/system/office-tools-pot.service << POTEOF
[Unit]
Description=Office Tools — bgutil PO-token provider (YouTube bot-check bypass)
After=network.target

[Service]
Type=simple
User=www-data
Group=www-data
WorkingDirectory=${POT_SERVER_DIR}/server
ExecStart=/usr/bin/node build/main.js --port ${POT_PORT}
Environment=TZ=UTC
Restart=on-failure
RestartSec=5s
StandardOutput=journal
StandardError=journal

[Install]
WantedBy=multi-user.target
POTEOF

    if command -v ufw &>/dev/null && ufw status 2>/dev/null | grep -q "Status: active"; then
        ufw deny "${POT_PORT}/tcp" >/dev/null 2>&1 || true
        info "ufw: external access to :${POT_PORT} denied (provider is localhost-only by policy)"
    fi

    systemctl daemon-reload
    systemctl enable office-tools-pot >/dev/null 2>&1
    systemctl restart office-tools-pot

    sleep 2
    if curl -s -m 5 "http://127.0.0.1:${POT_PORT}/ping" | grep -q version; then
        success "PO-token provider running on http://127.0.0.1:${POT_PORT}/ (v${pot_ver})"
    else
        warn "PO-token provider not responding — check: journalctl -u office-tools-pot -n 30"
    fi
}

# ─── yt-server (YouTube download backend) ─────────────────────────────────────
setup_yt_server() {
    section "Setting up yt-server (YouTube download backend)"

    mkdir -p "$YT_SERVER_DIR"
    rsync -a "$REPO_DIR/yt-server/" "$YT_SERVER_DIR/"

    cd "$YT_SERVER_DIR" && npm install --omit=dev && cd /

    # Ensure .env — never rewrite it. setup_yt_server runs on EVERY Option 1, so a
    # truncating write here would wipe operator keys (YTDLP_COOKIES most of all, whose
    # loss looks exactly like YouTube blocking the server again, with nothing logged).
    env_ensure "$YT_SERVER_DIR/.env" PORT 9000
    chmod 600 "$YT_SERVER_DIR/.env"
    chmod +x "$YT_SERVER_DIR/ytcookie-keepalive.sh" 2>/dev/null || true
    chown -R www-data:www-data "$YT_SERVER_DIR"

    setup_cookie_keepalive

    # Create systemd service
    cat > /etc/systemd/system/office-tools-cobalt.service << COBEOF
[Unit]
Description=Office Tools — yt-server YouTube Download Server
After=network.target

[Service]
Type=simple
User=www-data
Group=www-data
WorkingDirectory=${YT_SERVER_DIR}
ExecStart=/usr/bin/node server.js
Environment=TZ=UTC
EnvironmentFile=-${YT_SERVER_DIR}/.env
Restart=on-failure
RestartSec=5s
StandardOutput=journal
StandardError=journal

[Install]
WantedBy=multi-user.target
COBEOF

    systemctl daemon-reload
    systemctl enable office-tools-cobalt
    systemctl restart office-tools-cobalt

    sleep 3
    if systemctl is-active --quiet office-tools-cobalt; then
        success "yt-server running on http://127.0.0.1:9000/"
    else
        warn "yt-server failed to start — check: journalctl -u office-tools-cobalt -n 30"
    fi
}

# ─── Cookie keep-alive (cron) ─────────────────────────────────────────────────
# yt-server's /health reads <cookie-dir>/cookies.status to report "file:ok" vs
# "file:expired"; nothing writes that file except this cron. Without it /health is
# stuck on "file:unchecked" and cookie expiry is invisible until downloads break.
# The probe also makes yt-dlp rotate the cookie file, which is what keeps a parked
# session alive between real downloads.
setup_cookie_keepalive() {
    local cron_file="/etc/cron.d/office-tools-ytcookie"
    local log_file="${LOG_DIR}/ytcookie-keepalive.log"

    mkdir -p "$LOG_DIR"
    touch "$log_file"
    chown www-data:www-data "$log_file" 2>/dev/null || true

    # Runs as www-data — the user yt-server runs as, so the rotated cookie file keeps
    # its owner. A root-run probe would leave a root-owned cookies.txt behind and the
    # service could no longer write to it.
    cat > "$cron_file" << CRONEOF
# Auto-generated by deploy.sh — YouTube cookie keep-alive + expiry reporting.
# No-op when YTDLP_COOKIES is unset in ${YT_SERVER_DIR}/.env.
SHELL=/bin/bash
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
17 */6 * * * www-data ${YT_SERVER_DIR}/ytcookie-keepalive.sh >> ${log_file} 2>&1
CRONEOF
    chmod 644 "$cron_file"

    cat > /etc/logrotate.d/office-tools-ytcookie << 'LOGROTEOF'
/var/log/office-tools/ytcookie-keepalive.log {
    monthly
    rotate 3
    missingok
    notifempty
    compress
    copytruncate
}
LOGROTEOF

    success "Cookie keep-alive cron installed (every 6h, logs → ${log_file})"
}

sync_yt_server() {
    [[ -d "$YT_SERVER_DIR" ]] || return 0
    section "Syncing yt-server (YouTube download backend)"
    # --exclude='.env' keeps operator settings (YTDLP_COOKIES) across syncs.
    rsync -a --exclude='.env' --exclude='cookies.txt' --exclude='cookies.status' \
        "$REPO_DIR/yt-server/" "$YT_SERVER_DIR/"
    cd "$YT_SERVER_DIR" && npm install --omit=dev && cd /
    chmod +x "$YT_SERVER_DIR/ytcookie-keepalive.sh" 2>/dev/null || true
    chown -R www-data:www-data "$YT_SERVER_DIR"
    setup_cookie_keepalive
    systemctl restart office-tools-cobalt 2>/dev/null || true
    success "yt-server synced and restarted"
}

# ─── Repo & frontend ──────────────────────────────────────────────────────────
pull_repo() {
    section "Pulling Office Tools from GitHub"
    if [[ -d "$REPO_DIR/.git" ]]; then
        info "Repo found — fetching latest…"
        git -C "$REPO_DIR" fetch origin
        local branch
        branch=$(git -C "$REPO_DIR" branch --show-current 2>/dev/null || echo "master")
        git -C "$REPO_DIR" reset --hard "origin/$branch"
    else
        info "Cloning $REPO_URL…"
        mkdir -p "$(dirname "$REPO_DIR")"
        git clone "$REPO_URL" "$REPO_DIR"
    fi
    success "Repo: $(git -C "$REPO_DIR" log -1 --format='%h %s')"
}

sync_frontend() {
    local domain="${1:-}"
    section "Syncing frontend → $WEB_ROOT"
    mkdir -p "$WEB_ROOT"
    rsync -a --delete \
        --exclude='.git' \
        --exclude='.gitignore' \
        --exclude='backend' \
        --exclude='deploy.sh' \
        --exclude='undeploy.sh' \
        --exclude='*.md' \
        "$REPO_DIR/" "$WEB_ROOT/"
    chown -R www-data:www-data "$WEB_ROOT"
    chmod -R 755 "$WEB_ROOT"
    find "$WEB_ROOT" -type f -exec chmod 644 {} \;

    if [[ "$OS_FAMILY" == "rhel" ]]; then
        chcon -R -t httpd_sys_content_t "$WEB_ROOT" 2>/dev/null || true
    fi

    [[ -n "$domain" ]] && _patch_domain "$REPO_DIR" "$domain"
    [[ -n "$domain" ]] && _patch_domain "$WEB_ROOT"  "$domain"

    success "Frontend deployed to $WEB_ROOT"
}

_patch_domain() {
    local dir="$1" domain="$2"
    local cfg="$dir/js/config.js"
    if [[ -f "$cfg" ]]; then
        local apex; apex="$(_ipecho_apex "$domain")"
        sed -i "s|https://api\.yourdomain\.com|https://${domain}/tools-api|g" "$cfg"
        sed -i "s|https://ip4\.yourdomain\.com|https://ip4.${apex}|g"         "$cfg"
        sed -i "s|https://ip6\.yourdomain\.com|https://ip6.${apex}|g"         "$cfg"
        sed -i "s|https://yourdomain\.com|https://${domain}|g"              "$cfg"
    fi
    find "$dir" -name "*.html" -not -path "*/.git/*" \
        -exec sed -i "s|https://yourdomain\.com|https://${domain}|g" {} \;
    # Patch domain in sitemap.xml so Google sees the real URLs
    local sitemap="$dir/sitemap.xml"
    [[ -f "$sitemap" ]] && \
        sed -i "s|https://yourdomain\.com|https://${domain}|g" "$sitemap"
}

# ─── nginx config writers ──────────────────────────────────────────────────────
_nginx_enable() {
    if [[ "$OS_FAMILY" == "debian" ]]; then
        ln -sf "$NGINX_CONF_PATH" "$NGINX_ENABLED_PATH"
        rm -f /etc/nginx/sites-enabled/default
    fi
    nginx -t 2>&1 || die "nginx config test failed — check $NGINX_CONF_PATH"
    systemctl reload nginx
}

write_nginx_http() {
    local domain="$1"
    cat > "$NGINX_CONF_PATH" << NGINXEOF
# Office Tools — managed by deploy.sh (HTTP — certbot will add SSL)
server {
    listen 80;
    listen [::]:80;
    server_name ${domain};

    root  ${WEB_ROOT};
    index index.html;

    # SEO: strip explicit /index.html so canonical URL is always the directory
    location ~ ^(.*/)index\.html$ { return 301 \$1; }
    # SEO: strip trailing slash from .html file URLs (e.g. /pages/donate.html/)
    location ~ ^(.*\.html)/$ { return 301 \$1; }
    # SEO: enforce trailing slash on tool and page directory URLs (no file extension)
    location ~ ^(/tools/[^/.]+|/pages/[^/.]+)$ { return 301 \$uri/; }
    # Serve flat-file pages (pages/<x>.html) at their canonical directory URL /pages/<x>/
    # (donate/privacy live as pages/<x>.html but their canonical + sitemap use /pages/<x>/)
    location ~ ^/pages/([^/]+)/$ { try_files /pages/\$1.html /pages/\$1/index.html =404; }

    # Permanently removed pages — 410 Gone de-indexes faster/cleaner than a 404.
    # Add formerly-public URLs here when a tool/page is retired.
    location = /tools/wordle/ { return 410; }
    location ^~ /auth/        { return 410; }
    location ^~ /api/         { return 410; }   # old donate/wallet backend — live API is under /tools-api/
    location ~ ^/(playlist|shorts)(/|\$) { return 410; }   # retired YouTube routes

    location / { try_files \$uri/index.html \$uri \$uri.html =404; }

    # File Drop signaling — WebSocket upgrade (exact match wins over ^~ /tools-api/)
    location = /tools-api/drop-ws {
        proxy_pass            http://127.0.0.1:3001/drop-ws;
        proxy_http_version    1.1;
        proxy_set_header      Upgrade           \$http_upgrade;
        proxy_set_header      Connection        "upgrade";
        proxy_set_header      Host              \$host;
        proxy_set_header      X-Real-IP         \$remote_addr;
        proxy_set_header      X-Forwarded-For   \$proxy_add_x_forwarded_for;
        proxy_read_timeout    1h;
        proxy_send_timeout    1h;
    }
    # Chat Room signaling — WebSocket upgrade (exact match wins over ^~ /tools-api/)
    location = /tools-api/chat-ws {
        proxy_pass            http://127.0.0.1:3001/chat-ws;
        proxy_http_version    1.1;
        proxy_set_header      Upgrade           \$http_upgrade;
        proxy_set_header      Connection        "upgrade";
        proxy_set_header      Host              \$host;
        proxy_set_header      X-Real-IP         \$remote_addr;
        proxy_set_header      X-Forwarded-For   \$proxy_add_x_forwarded_for;
        proxy_read_timeout    1h;
        proxy_send_timeout    1h;
    }
    # Chat Room file uploads/downloads — up to 2 GB, long timeout for slow links
    # (longer prefix wins over ^~ /tools-api/; streamed, unbuffered)
    location ^~ /tools-api/api/chat/ {
        proxy_pass            http://127.0.0.1:3001/api/chat/;
        proxy_http_version    1.1;
        proxy_set_header      Host              \$host;
        proxy_set_header      X-Real-IP         \$remote_addr;
        proxy_set_header      X-Forwarded-For   \$proxy_add_x_forwarded_for;
        proxy_set_header      X-Forwarded-Proto \$scheme;
        client_max_body_size    2200M;
        proxy_read_timeout      3600s;
        proxy_send_timeout      3600s;
        proxy_request_buffering off;
        proxy_buffering         off;
    }
    location ^~ /tools-api/ {
        proxy_pass            http://127.0.0.1:3001/;
        proxy_http_version    1.1;
        proxy_set_header      Host              \$host;
        proxy_set_header      X-Real-IP         \$remote_addr;
        proxy_set_header      X-Forwarded-For   \$proxy_add_x_forwarded_for;
        proxy_set_header      X-Forwarded-Proto \$scheme;
        proxy_read_timeout    600s;
        proxy_send_timeout    600s;
        proxy_request_buffering off;
        proxy_buffering         off;
    }
    location ^~ /yt-api/ {
        proxy_pass              http://127.0.0.1:9000/;
        proxy_http_version      1.1;
        proxy_set_header        Host              \$host;
        proxy_set_header        X-Real-IP         \$remote_addr;
        proxy_set_header        X-Forwarded-For   \$proxy_add_x_forwarded_for;
        proxy_set_header        X-Forwarded-Proto \$scheme;
        proxy_read_timeout      600s;
        proxy_send_timeout      600s;
        proxy_request_buffering off;
        proxy_buffering         off;
    }
    location ~ /\.                           { deny all; return 404; }
    location /backend/                       { deny all; return 404; }
    location ~ \.(env|sh|json|md|toml|log)$ { deny all; return 404; }
}
NGINXEOF
    _nginx_enable
    success "nginx HTTP config written for ${domain}"
}

write_nginx_https() {
    local domain="$1"
    local ssl_cert="/etc/letsencrypt/live/${domain}/fullchain.pem"
    local ssl_key="/etc/letsencrypt/live/${domain}/privkey.pem"

    cat > "$NGINX_CONF_PATH" << NGINXEOF
# Office Tools — managed by deploy.sh

server {
    listen 80;
    listen [::]:80;
    server_name ${domain};
    return 301 https://\$host\$request_uri;
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name ${domain};

    ssl_certificate     ${ssl_cert};
    ssl_certificate_key ${ssl_key};
    ssl_protocols             TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers on;
    ssl_ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305;
    ssl_session_cache   shared:SSL:10m;
    ssl_session_timeout 1d;
    ssl_session_tickets off;

    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;
    add_header X-Frame-Options           "SAMEORIGIN"             always;
    add_header X-Content-Type-Options    "nosniff"                always;
    add_header X-XSS-Protection          "1; mode=block"          always;
    add_header Referrer-Policy           "strict-origin-when-cross-origin" always;
    add_header Permissions-Policy        "camera=(), microphone=(self), geolocation=()" always;

    gzip on; gzip_vary on;
    gzip_types text/plain text/css text/javascript application/javascript application/json image/svg+xml;
    gzip_min_length 1024;

    client_max_body_size 1100M;

    root  ${WEB_ROOT};
    index index.html;

    # SEO: strip explicit /index.html so canonical URL is always the directory
    location ~ ^(.*/)index\.html$ { return 301 \$1; }
    # SEO: strip trailing slash from .html file URLs (e.g. /pages/donate.html/)
    location ~ ^(.*\.html)/$ { return 301 \$1; }
    # SEO: enforce trailing slash on tool and page directory URLs (no file extension)
    location ~ ^(/tools/[^/.]+|/pages/[^/.]+)$ { return 301 \$uri/; }
    # Serve flat-file pages (pages/<x>.html) at their canonical directory URL /pages/<x>/
    # (donate/privacy live as pages/<x>.html but their canonical + sitemap use /pages/<x>/)
    location ~ ^/pages/([^/]+)/$ { try_files /pages/\$1.html /pages/\$1/index.html =404; }

    # Permanently removed pages — 410 Gone de-indexes faster/cleaner than a 404.
    # Add formerly-public URLs here when a tool/page is retired.
    location = /tools/wordle/ { return 410; }
    location ^~ /auth/        { return 410; }
    location ^~ /api/         { return 410; }   # old donate/wallet backend — live API is under /tools-api/
    location ~ ^/(playlist|shorts)(/|\$) { return 410; }   # retired YouTube routes

    location / { try_files \$uri/index.html \$uri \$uri.html =404; }

    location ~* \.(css|js|png|jpg|jpeg|gif|ico|svg|woff2|woff)$ {
        expires 7d;
        add_header Cache-Control "public, immutable";
    }

    # File Drop signaling — WebSocket upgrade (exact match wins over ^~ /tools-api/)
    location = /tools-api/drop-ws {
        proxy_pass            http://127.0.0.1:3001/drop-ws;
        proxy_http_version    1.1;
        proxy_set_header      Upgrade           \$http_upgrade;
        proxy_set_header      Connection        "upgrade";
        proxy_set_header      Host              \$host;
        proxy_set_header      X-Real-IP         \$remote_addr;
        proxy_set_header      X-Forwarded-For   \$proxy_add_x_forwarded_for;
        proxy_read_timeout    1h;
        proxy_send_timeout    1h;
    }
    # Chat Room signaling — WebSocket upgrade (exact match wins over ^~ /tools-api/)
    location = /tools-api/chat-ws {
        proxy_pass            http://127.0.0.1:3001/chat-ws;
        proxy_http_version    1.1;
        proxy_set_header      Upgrade           \$http_upgrade;
        proxy_set_header      Connection        "upgrade";
        proxy_set_header      Host              \$host;
        proxy_set_header      X-Real-IP         \$remote_addr;
        proxy_set_header      X-Forwarded-For   \$proxy_add_x_forwarded_for;
        proxy_read_timeout    1h;
        proxy_send_timeout    1h;
    }
    # Chat Room file uploads/downloads — up to 2 GB, long timeout for slow links
    # (longer prefix wins over ^~ /tools-api/; streamed, unbuffered)
    location ^~ /tools-api/api/chat/ {
        proxy_pass            http://127.0.0.1:3001/api/chat/;
        proxy_http_version    1.1;
        proxy_set_header      Host              \$host;
        proxy_set_header      X-Real-IP         \$remote_addr;
        proxy_set_header      X-Forwarded-For   \$proxy_add_x_forwarded_for;
        proxy_set_header      X-Forwarded-Proto \$scheme;
        client_max_body_size    2200M;
        proxy_read_timeout      3600s;
        proxy_send_timeout      3600s;
        proxy_request_buffering off;
        proxy_buffering         off;
    }
    location ^~ /tools-api/ {
        proxy_pass            http://127.0.0.1:3001/;
        proxy_http_version    1.1;
        proxy_set_header      Host              \$host;
        proxy_set_header      X-Real-IP         \$remote_addr;
        proxy_set_header      X-Forwarded-For   \$proxy_add_x_forwarded_for;
        proxy_set_header      X-Forwarded-Proto \$scheme;
        proxy_read_timeout    600s;
        proxy_send_timeout    600s;
        proxy_request_buffering off;
        proxy_buffering         off;
    }
    location ^~ /yt-api/ {
        proxy_pass              http://127.0.0.1:9000/;
        proxy_http_version      1.1;
        proxy_set_header        Host              \$host;
        proxy_set_header        X-Real-IP         \$remote_addr;
        proxy_set_header        X-Forwarded-For   \$proxy_add_x_forwarded_for;
        proxy_set_header        X-Forwarded-Proto \$scheme;
        proxy_read_timeout      600s;
        proxy_send_timeout      600s;
        proxy_request_buffering off;
        proxy_buffering         off;
    }

    location ~ /\.                           { deny all; return 404; }
    location /backend/                       { deny all; return 404; }
    location ~ \.(env|sh|json|md|toml|log)$ { deny all; return 404; }
}
NGINXEOF
    _nginx_enable
    success "nginx HTTPS config hardened for ${domain}"
}

get_ssl() {
    local domain="$1" email="$2"
    section "Getting Let's Encrypt SSL for ${domain}"
    echo -e "  ${DIM}[i] Cloudflare users: if certificate generation fails, try setting your${RESET}"
    echo -e "  ${DIM}    DNS record to ${BOLD}DNS only${RESET}${DIM} (grey cloud) and re-run. You can re-enable${RESET}"
    echo -e "  ${DIM}    proxying after the certificate is issued.${RESET}"
    echo ""
    certbot --nginx -d "$domain" \
        --non-interactive --agree-tos \
        -m "$email" --redirect
    success "SSL certificate issued"
}

# ─── IP-echo subdomains (ip4. / ip6.) — Option-2 "both v4+v6" feature ───────────
# Two family-pinned hostnames let a browser learn BOTH its IPv4 and IPv6 by fetching
# each one: ip4.<apex> must be A-only DNS, ip6.<apex> AAAA-only. A single hostname
# can never return both (one connection = one family), so this is the only real way.
# Kept in an ISOLATED conf file with BEST-EFFORT certbot: any failure here warns and
# returns 0 — it can never break the main site or fail the deploy.

# Derive the apex (last two labels) so tools.grin.money → grin.money → ip4.grin.money.
# Good for single-label TLDs (.com/.money/.io); set the hosts by hand for .co.uk etc.
_ipecho_apex() { echo "$1" | awk -F. '{ if (NF>=2) print $(NF-1)"."$NF; else print $0 }'; }

_ipecho_conf_path() {
    if [[ "$OS_FAMILY" == "debian" ]]; then
        echo "/etc/nginx/sites-available/office-tools-ipecho"
    else
        echo "/etc/nginx/conf.d/office-tools-ipecho.conf"
    fi
}

setup_ip_echo() {
    local domain="$1" email="$2"
    local apex h4 h6 conf
    apex="$(_ipecho_apex "$domain")"
    h4="ip4.${apex}"; h6="ip6.${apex}"
    conf="$(_ipecho_conf_path)"

    section "IP-echo subdomains — ${h4} / ${h6} (best-effort)"

    # Two SEPARATE server blocks + two SEPARATE certs on purpose: if the server has no
    # public IPv6, ip6's cert can't validate — decoupling keeps ip4 working regardless.
    # HTTP-only first so certbot can validate + inject SSL (avoids the cert chicken-and-egg).
    cat > "$conf" << IPEOF
# Office Tools — IP-echo subdomains (managed by deploy.sh)
# ip4.<apex> = A-only DNS, ip6.<apex> = AAAA-only → each forces one family so a
# browser can read BOTH addresses. Every path returns the caller's IP via backend /ip
# (query strings like ?format=json pass through). Open CORS comes from the backend.
server {
    listen 80;
    listen [::]:80;
    server_name ${h4};
    location / {
        proxy_pass            http://127.0.0.1:3001/ip;
        proxy_http_version    1.1;
        proxy_set_header      Host              \$host;
        proxy_set_header      X-Real-IP         \$remote_addr;
        proxy_set_header      X-Forwarded-For   \$proxy_add_x_forwarded_for;
        proxy_set_header      X-Forwarded-Proto \$scheme;
    }
}
server {
    listen 80;
    listen [::]:80;
    server_name ${h6};
    location / {
        proxy_pass            http://127.0.0.1:3001/ip;
        proxy_http_version    1.1;
        proxy_set_header      Host              \$host;
        proxy_set_header      X-Real-IP         \$remote_addr;
        proxy_set_header      X-Forwarded-For   \$proxy_add_x_forwarded_for;
        proxy_set_header      X-Forwarded-Proto \$scheme;
    }
}
IPEOF

    [[ "$OS_FAMILY" == "debian" ]] && ln -sf "$conf" "/etc/nginx/sites-enabled/office-tools-ipecho"

    if ! nginx -t 2>/dev/null; then
        warn "IP-echo nginx test failed — removing its conf, main site untouched. (check $conf)"
        rm -f "$conf"
        [[ "$OS_FAMILY" == "debian" ]] && rm -f "/etc/nginx/sites-enabled/office-tools-ipecho"
        return 0
    fi
    systemctl reload nginx

    # Independent certs — ip4 needs its A record live; ip6 needs a working public IPv6 (AAAA).
    if certbot --nginx -d "$h4" --non-interactive --agree-tos -m "$email" --redirect; then
        success "IPv4 host live: https://${h4}"
    else
        warn "certbot could not issue ${h4} — DNS for ip4. not propagated yet. Re-run Option 2 later."
    fi
    if certbot --nginx -d "$h6" --non-interactive --agree-tos -m "$email" --redirect; then
        success "IPv6 host live: https://${h6}"
    else
        warn "certbot could not issue ${h6} — no public IPv6 on this server, or ip6. AAAA not propagated."
        warn "ip4 still works; the 'Both at once' card will show ipv6:null until ip6. has a cert."
    fi
}

remove_ip_echo() {
    local conf; conf="$(_ipecho_conf_path)"
    [[ -e "$conf" ]] || return 0
    local apex h4 h6
    apex="$(_ipecho_apex "${1:-$DOMAIN}")"; h4="ip4.${apex}"; h6="ip6.${apex}"
    rm -f "$conf"
    [[ "$OS_FAMILY" == "debian" ]] && rm -f "/etc/nginx/sites-enabled/office-tools-ipecho"
    certbot delete --cert-name "$h4" --non-interactive 2>/dev/null || true
    nginx -t 2>/dev/null && systemctl reload nginx || true
    success "IP-echo subdomains removed (${h4} / ${h6})"
}

# ─── Backend ──────────────────────────────────────────────────────────────────
# Write/update NOTIFY_EMAIL and NOTIFY_EMAIL_2 in existing .env
_update_notify_env() {
    local e1="${1:-}" e2="${2:-}"
    [[ ! -f "$BACKEND_DIR/.env" ]] && return 0
    for key_val in "NOTIFY_EMAIL=${e1}" "NOTIFY_EMAIL_2=${e2}"; do
        local key="${key_val%%=*}"
        local val="${key_val#*=}"
        if grep -q "^${key}=" "$BACKEND_DIR/.env" 2>/dev/null; then
            sed -i "s|^${key}=.*|${key}=${val}|" "$BACKEND_DIR/.env"
        else
            echo "${key}=${val}" >> "$BACKEND_DIR/.env"
        fi
    done
}

# ─── TURN relay (coturn) — File Drop WebRTC fallback ───────────────────────────
# Installs+configures coturn with the REST/`use-auth-secret` scheme so the API
# server can mint short-lived TURN credentials (see /api/tools/turn). Idempotent
# and non-fatal: on any failure it warns and returns 0 so the deploy continues —
# File Drop still works over direct P2P, just without the relay fallback.
setup_turn() {
    local domain="$1" secret="$2" ext_ip="${3:-}"
    section "TURN relay setup — coturn (File Drop fallback)"

    # On a cloud VPS with 1:1 NAT (public IP not on the interface), coturn must be
    # told the public↔private mapping or it advertises the private IP as the relay
    # candidate. Passed as <PUBLIC>/<PRIVATE> from _provision_turn only when they differ.
    local ext_line=""
    [[ -n "$ext_ip" ]] && ext_line="external-ip=${ext_ip}"

    # coturn reads a different config path per distro: Debian → /etc/turnserver.conf
    # (plus the /etc/default/coturn enable gate); EPEL on Rocky/Alma → /etc/coturn/
    # turnserver.conf. Writing to the wrong one would leave coturn running on
    # package defaults (no auth secret) — broken. Pick the path the package uses.
    local turn_conf="/etc/turnserver.conf"
    if [[ "$OS_FAMILY" == "debian" ]]; then
        DEBIAN_FRONTEND=noninteractive apt-get install -y coturn >/dev/null 2>&1 \
            || { warn "coturn install failed — File Drop will use direct P2P only"; return 0; }
        # Debian gates the daemon behind /etc/default/coturn
        if grep -q '^#*TURNSERVER_ENABLED=' /etc/default/coturn 2>/dev/null; then
            sed -i 's/^#*TURNSERVER_ENABLED=.*/TURNSERVER_ENABLED=1/' /etc/default/coturn
        else
            echo 'TURNSERVER_ENABLED=1' >> /etc/default/coturn
        fi
    else
        # coturn on Rocky/Alma comes from EPEL — install fails (non-fatal) if EPEL absent
        dnf install -y coturn >/dev/null 2>&1 || yum install -y coturn >/dev/null 2>&1 \
            || { warn "coturn install failed (EPEL enabled?) — File Drop will use direct P2P only"; return 0; }
        mkdir -p /etc/coturn
        turn_conf="/etc/coturn/turnserver.conf"
    fi

    # Plain turn: on 3478 (udp+tcp) only. We deliberately do NOT configure turns:
    # (TLS 5349): the frontend advertises only turn: URLs, the relayed media is
    # already end-to-end DTLS-encrypted, and pointing coturn at the root-only LE
    # privkey would make a non-root coturn (EL) fail to start for zero client gain.
    # turns: can be added later (needs a cert the coturn user can read).
    cat > "$turn_conf" << TURNEOF
# Office Tools — File Drop TURN relay (managed by deploy.sh)
listening-port=3478
fingerprint
use-auth-secret
static-auth-secret=${secret}
realm=${domain}
${ext_line}
no-cli
no-tcp-relay
no-multicast-peers
min-port=49152
max-port=65535
# SSRF hardening — never relay to loopback/private/link-local ranges
denied-peer-ip=0.0.0.0-0.255.255.255
denied-peer-ip=10.0.0.0-10.255.255.255
denied-peer-ip=100.64.0.0-100.127.255.255
denied-peer-ip=127.0.0.0-127.255.255.255
denied-peer-ip=169.254.0.0-169.254.255.255
denied-peer-ip=172.16.0.0-172.31.255.255
denied-peer-ip=192.168.0.0-192.168.255.255
denied-peer-ip=::1
denied-peer-ip=fc00::-fdff:ffff:ffff:ffff:ffff:ffff:ffff:ffff
denied-peer-ip=fe80::-febf:ffff:ffff:ffff:ffff:ffff:ffff:ffff
TURNEOF
    # The config holds the auth secret, so keep it non-world-readable — but coturn
    # runs as a non-root user on EL (coturn) and may on Debian (turnserver), so a
    # 600 root:root file would be UNREADABLE to the daemon and it wouldn't start.
    # 640 root:<service-group> lets the daemon read it; falls back to root:root
    # (fine — Debian's unit runs as root) when no such group exists.
    chmod 640 "$turn_conf"
    for _grp in coturn turnserver; do
        if getent group "$_grp" >/dev/null 2>&1; then chown "root:$_grp" "$turn_conf"; break; fi
    done

    # Firewall: TURN signaling (3478 udp+tcp) + relay media range
    if command -v firewall-cmd &>/dev/null && systemctl is-active --quiet firewalld 2>/dev/null; then
        firewall-cmd --permanent --add-port=3478/udp --add-port=3478/tcp &>/dev/null
        firewall-cmd --permanent --add-port=49152-65535/udp &>/dev/null
        firewall-cmd --reload &>/dev/null
    fi
    if command -v ufw &>/dev/null && ufw status 2>/dev/null | grep -q "Status: active"; then
        ufw allow 3478/udp >/dev/null 2>&1 || true
        ufw allow 3478/tcp >/dev/null 2>&1 || true
        ufw allow 49152:65535/udp >/dev/null 2>&1 || true
    fi

    systemctl enable coturn >/dev/null 2>&1 || true
    if systemctl restart coturn >/dev/null 2>&1; then
        success "coturn TURN relay running on :3478 (realm ${domain})"
    else
        warn "coturn failed to start — check: journalctl -u coturn (File Drop still works P2P)"
    fi
}

# Set KEY=VALUE in the backend .env — update in place or append. Value must not
# contain the sed delimiter (|); TURN URLs/secret/domain never do.
_set_env_kv() {
    local key="$1" val="$2" envf="$BACKEND_DIR/.env"
    if grep -q "^${key}=" "$envf" 2>/dev/null; then
        sed -i "s|^${key}=.*|${key}=${val}|" "$envf"
    else
        echo "${key}=${val}" >> "$envf"
    fi
}

# The IP a remote client actually sees (asks an external echo; falls back to the
# default-route source IP). TURN clients must reach this IP directly.
_detect_public_ip() {
    local ip="" url
    for url in "https://api.ipify.org" "https://ipv4.icanhazip.com" "https://ifconfig.me/ip"; do
        # || true: under `set -e`+pipefail a failed curl would otherwise abort the
        # loop before the fallback URLs are tried.
        ip=$(curl -4 -fsS --max-time 5 "$url" 2>/dev/null | tr -d '[:space:]') || true
        [[ "$ip" =~ ^[0-9]{1,3}(\.[0-9]{1,3}){3}$ ]] && { echo "$ip"; return 0; }
    done
    ip -4 route get 1.1.1.1 2>/dev/null | grep -oP 'src \K[0-9.]+' | head -1 || true
}
# The IP actually bound on the interface (private on a NAT box, public otherwise).
_detect_local_ip() {
    ip -4 route get 1.1.1.1 2>/dev/null | grep -oP 'src \K[0-9.]+' | head -1 || true
}

# Idempotently ensure TURN settings exist in .env and coturn is provisioned.
# Safe on first-time setup AND every update (sync_backend): reuses an existing
# TURN_SECRET (never rotates a working one), then (re)configures coturn.
# No-op without a domain or an existing .env.
#
# TURN is advertised on the server's PUBLIC IP, not the site domain: a CDN/proxy
# in front of the domain (e.g. Cloudflare's orange cloud) only forwards 80/443, so
# UDP/TCP 3478 sent to the proxied hostname dies at the edge and never reaches
# coturn. The raw IP goes straight to the box. (Trade-off: the /api/tools/turn
# response then exposes the origin IP — unavoidable for TURN to function.)
_provision_turn() {
    local domain="$1" envf="$BACKEND_DIR/.env"
    if [[ -z "$domain" || ! -f "$envf" ]]; then return 0; fi

    local pub_ip local_ip host ext_ip=""
    pub_ip="$(_detect_public_ip)"  || true
    local_ip="$(_detect_local_ip)" || true
    if [[ -n "$pub_ip" ]]; then
        host="$pub_ip"
        # 1:1 NAT (cloud): interface holds a private IP ≠ the public IP → tell coturn.
        [[ -n "$local_ip" && "$local_ip" != "$pub_ip" ]] && ext_ip="${pub_ip}/${local_ip}"
    else
        warn "Could not detect public IP — TURN will use ${domain} (fails if behind a proxy/CDN)"
        host="$domain"
    fi

    local secret
    # || true: grep exits 1 (→ pipefail) when TURN_SECRET isn't in .env yet (fresh
    # box); without the guard `set -e` would abort the deploy on first-time setup.
    secret=$(grep -E '^TURN_SECRET=' "$envf" 2>/dev/null | head -1 | cut -d= -f2-) || true
    [[ -z "$secret" ]] && secret="$(openssl rand -hex 32)"
    _set_env_kv TURN_URLS   "turn:${host}:3478?transport=udp,turn:${host}:3478?transport=tcp"
    _set_env_kv TURN_SECRET "$secret"
    grep -q '^TURN_TTL=' "$envf" 2>/dev/null || echo 'TURN_TTL=3600' >> "$envf"
    chmod 600 "$envf"
    setup_turn "$domain" "$secret" "$ext_ip"
}

setup_backend_first() {
    local domain="$1"
    local notify_email="${2:-}"
    local notify_email2="${3:-}"

    section "Backend setup — API server"

    mkdir -p "$BACKEND_DIR"
    mkdir -p /opt/office-tools/data/uploads
    chown -R www-data:www-data /opt/office-tools/data
    rsync -a "$REPO_DIR/backend/" "$BACKEND_DIR/"

    cat > "$BACKEND_DIR/.env" << ENVEOF
# Office Tools backend config
PORT=3001
CORS_ORIGINS=https://${domain}
NOTIFY_EMAIL=${notify_email}
NOTIFY_EMAIL_2=${notify_email2}
# Per-IP/min cap for the public port-check probe endpoints (default 600, clamp 10–2000).
# Raise for many miners behind one shared NAT/VPN (e.g. 1000); restart the service after.
PROBE_RATE_PER_MIN=600
ENVEOF
    chmod 600 "$BACKEND_DIR/.env"

    # TURN relay for File Drop — idempotent; the same helper runs on every
    # sync_backend so existing deployments get it on update, not just here.
    _provision_turn "$domain"

    cd "$BACKEND_DIR" && npm install --omit=dev && cd /
    success "Backend files ready at $BACKEND_DIR"

    # Systemd service
    section "Creating systemd service"
    cat > /etc/systemd/system/office-tools-api.service << PAYEOF
[Unit]
Description=Office Tools — API Server
After=network.target
[Service]
Type=simple
User=www-data
Group=www-data
WorkingDirectory=${BACKEND_DIR}
ExecStart=/usr/bin/node office-tools-server.js
Environment=TZ=UTC
EnvironmentFile=${BACKEND_DIR}/.env
Restart=on-failure
RestartSec=5s
StandardOutput=journal
StandardError=journal
[Install]
WantedBy=multi-user.target
PAYEOF

    systemctl daemon-reload
    systemctl enable office-tools-api
    systemctl start office-tools-api || \
        warn "API server failed to start — check: journalctl -u office-tools-api"

    success "Backend service enabled and started"
}

sync_backend() {
    section "Syncing backend files"
    rsync -a --exclude='.env' "$REPO_DIR/backend/" "$BACKEND_DIR/"
    cd "$BACKEND_DIR" && npm install --omit=dev && cd /
    # Ensure SQLite data directory exists and is owned by the service user
    mkdir -p /opt/office-tools/data/uploads
    chown -R www-data:www-data /opt/office-tools/data
    # Ensure the File Drop TURN relay is provisioned (idempotent). Runs here so
    # existing deployments pick up TURN on a normal update, before the restart
    # below so the API loads the freshly-seeded TURN_SECRET/TURN_URLS.
    _provision_turn "${DOMAIN:-}"
    systemctl restart office-tools-api 2>/dev/null || true
    success "Backend synced and service restarted"
}

# ─── Summary printer ──────────────────────────────────────────────────────────
print_summary() {
    local domain="$1"
    echo ""
    echo -e "${BOLD}${GREEN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${RESET}"
    echo -e "${BOLD}${GREEN}  ✔  https://${domain}  is live${RESET}"
    echo -e "${BOLD}${GREEN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${RESET}"
    echo ""
    echo -e "  ${BOLD}Site:${RESET}           https://${domain}/"
    echo -e "  ${BOLD}YT Downloader:${RESET}  https://${domain}/tools/yt-downloader/"
    echo -e "  ${BOLD}YT API:${RESET}         https://${domain}/yt-api/   ${DIM}(yt-server, port 9000)${RESET}"
    echo -e "  ${BOLD}Web root:${RESET}       ${WEB_ROOT}"
    echo -e "  ${BOLD}nginx config:${RESET}   ${NGINX_CONF_PATH}"
    echo -e "  ${BOLD}Repo:${RESET}           ${REPO_DIR}"
    echo -e "  ${BOLD}Logs:${RESET}           ${LOG_DIR}/"
    echo ""
}

# ─── Banner & status ──────────────────────────────────────────────────────────
show_banner() {
    clear
    echo ""
    echo -e "${BOLD}${CYAN}╔═══════════════════════════════════════════════════════╗${RESET}"
    echo -e "${BOLD}${CYAN}║       Office Tools — Deploy Manager  v2026.07.23      ║${RESET}"
    echo -e "${BOLD}${CYAN}║       github.com/noobvie/Office_Tools                 ║${RESET}"
    echo -e "${BOLD}${CYAN}╚═══════════════════════════════════════════════════════╝${RESET}"
    echo ""
    echo -e "  ${DIM}OS: ${OS_NAME}${RESET}"
}

show_status() {
    load_conf
    echo -e "  ${BOLD}Current status${RESET}"
    echo -e "  ──────────────────────────────────────────────────"

    if [[ -n "$DOMAIN" ]]; then
        echo -e "  ${GREEN}●${RESET} Domain       : ${BOLD}${DOMAIN}${RESET}"
    else
        echo -e "  ${DIM}○ Domain       : not configured${RESET}"
    fi

    if [[ -d "$REPO_DIR/.git" ]]; then
        local commit; commit=$(git -C "$REPO_DIR" log -1 --format='%h %s' 2>/dev/null || echo "unknown")
        echo -e "  ${GREEN}●${RESET} Repo         : ${DIM}${commit}${RESET}"
    else
        echo -e "  ${DIM}○ Repo         : not cloned${RESET}"
    fi

    # Core services (yt-server excluded — managed separately via Option 6)
    local svcs=("nginx" "office-tools-api")
    for svc in "${svcs[@]}"; do
        if systemctl is-active --quiet "$svc" 2>/dev/null; then
            echo -e "  ${GREEN}●${RESET} ${svc}  ${DIM}running${RESET}"
        elif systemctl list-unit-files "${svc}.service" 2>/dev/null | grep -q "${svc}"; then
            echo -e "  ${YELLOW}●${RESET} ${svc}  ${DIM}stopped${RESET}"
        fi
    done

    echo ""
}

# ─── Option 1: Install / Update ───────────────────────────────────────────────
opt_1_install_update() {
    show_banner
    section "Option 1 — Install / Update"

    echo -e "  This will:"
    echo -e "    ${CYAN}·${RESET} Set system timezone  ${DIM}→ UTC (required for consistent timestamps)${RESET}"
    echo -e "    ${CYAN}·${RESET} Update OS packages   ${DIM}(${OS_FAMILY})${RESET}"
    echo -e "    ${CYAN}·${RESET} Install / update:    nginx · certbot · Node.js · git · curl"
    echo -e "    ${CYAN}·${RESET} Install / update:    ffmpeg · yt-dlp · PO-token provider · yt-server ${DIM}(YouTube downloader backend)${RESET}"
    echo -e "    ${CYAN}·${RESET} Pull latest code     ${DIM}(Office Tools GitHub)${RESET}"
    echo -e "    ${CYAN}·${RESET} Sync frontend files  ${DIM}→ $WEB_ROOT${RESET}"
    echo -e "    ${CYAN}·${RESET} Restart services     ${DIM}(if already configured)${RESET}"
    echo ""
    ask_proceed "Proceed" || return 0

    mkdir -p "$LOG_DIR"
    local logf="$LOG_DIR/install_$(date +%Y%m%d_%H%M%S).log"
    info "Logging to: $logf"

    (
        set -euo pipefail
        exec > >(tee "$logf") 2>&1
        enforce_utc_timezone
        pkg_update_os
        install_base_packages
        install_nodejs
        install_ffmpeg
        install_ytdlp
        setup_pot_provider
        pull_repo
        load_conf
        sync_frontend "${DOMAIN:-}"
        # Always call setup_yt_server — handles both fresh install and updates,
        # and always (re-)writes the systemd service file.
        setup_yt_server
        if [[ -n "$DOMAIN" ]]; then
            [[ -d "$BACKEND_DIR" ]] && sync_backend || true
            systemctl reload nginx 2>/dev/null || true
        fi
    ) || warn "Some steps had errors — check $logf"

    load_conf
    if [[ -n "$DOMAIN" ]]; then
        success "Update complete — https://${DOMAIN}"
    else
        success "Packages installed. Run Option 2 to configure a domain."
    fi

    press_enter
}

# ─── Option 2: Add / Configure Domain ─────────────────────────────────────────
opt_2_add_domain() {
    show_banner
    section "Option 2 — Add / Configure Domain"

    load_conf

    # Prerequisites check
    if ! command -v nginx &>/dev/null; then
        warn "nginx not installed. Run Option 1 first."
        press_enter; return 0
    fi
    if ! command -v certbot &>/dev/null; then
        warn "certbot not installed. Run Option 1 first."
        press_enter; return 0
    fi
    if [[ ! -d "$REPO_DIR/.git" ]]; then
        warn "Repository not cloned. Run Option 1 first."
        press_enter; return 0
    fi

    # Domain prompt
    echo ""
    [[ -n "$DOMAIN" ]] && echo -e "  ${DIM}Current domain: ${DOMAIN}${RESET}"
    echo -e "  ${DIM}(enter 0 at any prompt to cancel and return to menu)${RESET}"
    while true; do
        local _prompt="  ${BOLD}Domain name${RESET}"
        [[ -n "$DOMAIN" ]] && _prompt+=" (Enter = keep ${DIM}[$DOMAIN]${RESET})"
        _prompt+=": "
        echo -ne "$_prompt"
        read -r _new
        [[ "$_new" == "0" ]] && return 0
        if [[ -n "$_new" ]]; then DOMAIN="$_new"; break
        elif [[ -n "$DOMAIN" ]]; then break
        else warn "Domain cannot be empty."; fi
    done

    # Email prompt
    while true; do
        local _eprompt="  ${BOLD}Email for SSL${RESET}"
        [[ -n "$EMAIL" ]] && _eprompt+=" (Enter = keep ${DIM}[$EMAIL]${RESET})"
        _eprompt+=": "
        echo -ne "$_eprompt"
        read -r _new
        [[ "$_new" == "0" ]] && return 0
        if [[ -n "$_new" ]]; then EMAIL="$_new"; break
        elif [[ -n "$EMAIL" ]]; then break
        else warn "Email cannot be empty."; fi
    done

    # Backend — only prompt on first install
    local _do_backend=false
    if [[ ! -d "$BACKEND_DIR" ]] || [[ ! -f "$BACKEND_DIR/.env" ]]; then
        echo ""
        echo -e "  ${DIM}Backend service (API server) is optional.${RESET}"
        echo -ne "  Set up backend? [Y/n]: "
        read -r _b; _b="${_b:-Y}"
        [[ "${_b,,}" == "y" ]] && _do_backend=true && SETUP_BACKEND="y"
    else
        info "Backend already installed — will sync files only"
    fi

    # Notify emails for feedback submissions
    local _notify_email="" _notify_email2=""
    _notify_email=$(grep '^NOTIFY_EMAIL=' "$BACKEND_DIR/.env" 2>/dev/null \
        | cut -d= -f2- | tr -d '"' | tr -d "'")
    _notify_email2=$(grep '^NOTIFY_EMAIL_2=' "$BACKEND_DIR/.env" 2>/dev/null \
        | cut -d= -f2- | tr -d '"' | tr -d "'")
    echo ""
    echo -e "  ${BOLD}Feedback notification emails${RESET} ${DIM}(where to send user reports — leave blank to skip)${RESET}"
    local _p1="  Primary email"
    [[ -n "$_notify_email" ]] && _p1+=" ${DIM}[${_notify_email}]${RESET}"
    echo -ne "${_p1}: "
    read -r _new_ne; [[ "$_new_ne" == "0" ]] && return 0
    [[ -n "$_new_ne" ]] && _notify_email="$_new_ne"
    local _p2="  Secondary email ${DIM}(optional)"
    [[ -n "$_notify_email2" ]] && _p2+=" [${_notify_email2}]"
    _p2+="${RESET}"
    echo -ne "${_p2}: "
    read -r _new_ne2; [[ "$_new_ne2" == "0" ]] && return 0
    [[ -n "$_new_ne2" ]] && _notify_email2="$_new_ne2"

    echo ""
    echo -e "  Domain        : ${BOLD}${DOMAIN}${RESET}"
    echo -e "  SSL email     : ${EMAIL}"
    if [[ -n "$_notify_email" ]]; then
        echo -e "  Notify        : ${DIM}(configured)${RESET}"
    else
        echo -e "  Notify        : ${DIM}(disabled)${RESET}"
    fi
    echo -e "  Web root      : $WEB_ROOT"
    echo ""
    ask_proceed "Proceed" || return 0

    mkdir -p "$LOG_DIR"
    local logf="$LOG_DIR/domain_$(date +%Y%m%d_%H%M%S).log"
    info "Logging to: $logf"

    (
        set -euo pipefail
        exec > >(tee "$logf") 2>&1

        sync_frontend "$DOMAIN"
        write_nginx_http "$DOMAIN"
        get_ssl "$DOMAIN" "$EMAIL"
        write_nginx_https "$DOMAIN"

        if [[ "$_do_backend" == true ]]; then
            setup_backend_first "$DOMAIN" "$_notify_email" "$_notify_email2"
        elif [[ -d "$BACKEND_DIR" ]]; then
            sync_backend
            _update_notify_env "$_notify_email" "$_notify_email2"
            systemctl restart office-tools-api 2>/dev/null || true
        fi

        # Optional ip4./ip6. subdomains (best-effort; never fails the deploy)
        setup_ip_echo "$DOMAIN" "$EMAIL" || true
    ) || { warn "Errors during setup — check $logf"; press_enter; return 0; }

    save_conf
    print_summary "$DOMAIN"
    press_enter
}

# ─── Option 3: Remove / Switch Domain ─────────────────────────────────────────
opt_3_remove_switch() {
    show_banner
    section "Option 3 — Remove / Switch Domain"

    load_conf

    if [[ -z "$DOMAIN" ]]; then
        warn "No domain configured. Nothing to remove or switch."
        press_enter; return 0
    fi

    echo -e "  Configured domain: ${BOLD}${DOMAIN}${RESET}"
    echo ""
    echo -e "    ${YELLOW}a)${RESET}  Remove domain         ${DIM}nginx config + SSL cert only — files kept${RESET}"
    echo -e "    ${YELLOW}b)${RESET}  Switch to new domain  ${DIM}remove old config, set up new domain + SSL${RESET}"
    echo -e "    ${YELLOW}0)${RESET}  Back"
    echo ""
    echo -ne "  Choose [a/b/0]: "; read -r _sub

    case "${_sub,,}" in
      a)
        echo ""
        echo -ne "  ${BOLD}${YELLOW}Type 'yes' to confirm removing config for ${DOMAIN}: ${RESET}"
        read -r _c
        [[ "$_c" != "yes" ]] && info "Aborted."; [[ "$_c" != "yes" ]] && press_enter && return 0

        # Remove nginx config
        if [[ -e "$NGINX_CONF_PATH" ]]; then
            rm -f "$NGINX_CONF_PATH"
            success "Removed: $NGINX_CONF_PATH"
        fi
        if [[ -n "$NGINX_ENABLED_PATH" && -L "$NGINX_ENABLED_PATH" ]]; then
            rm -f "$NGINX_ENABLED_PATH"
            success "Removed symlink: $NGINX_ENABLED_PATH"
        fi

        # Remove the optional ip4./ip6. echo subdomains too
        remove_ip_echo "$DOMAIN" || true

        if nginx -t 2>/dev/null; then
            systemctl reload nginx
            success "nginx reloaded"
        else
            warn "nginx config test failed — check /etc/nginx/ manually"
        fi

        # Remove SSL cert
        if [[ -d "/etc/letsencrypt/live/${DOMAIN}" ]]; then
            certbot delete --cert-name "$DOMAIN" --non-interactive 2>/dev/null || {
                rm -rf "/etc/letsencrypt/live/${DOMAIN}"
                rm -f  "/etc/letsencrypt/renewal/${DOMAIN}.conf"
            }
            success "SSL certificate removed for $DOMAIN"
        fi

        local _old="$DOMAIN"
        DOMAIN=""
        save_conf
        success "Domain '$_old' removed. Use Option 2 to configure a new domain."
        ;;

      b)
        echo ""
        while true; do
            echo -ne "  ${BOLD}New domain name${RESET}: "
            read -r _new
            [[ -n "$_new" ]] && break
            warn "Domain cannot be empty."
        done
        echo -ne "  ${BOLD}Email for SSL${RESET} (Enter = keep [$EMAIL]): "
        read -r _em; [[ -n "$_em" ]] && EMAIL="$_em"

        echo ""
        echo -e "  Will remove: ${BOLD}${DOMAIN}${RESET}"
        echo -e "  Will set up: ${BOLD}${_new}${RESET}"
        echo ""
        ask_proceed "Proceed" || return 0

        mkdir -p "$LOG_DIR"
        local logf="$LOG_DIR/switch_$(date +%Y%m%d_%H%M%S).log"

        (
            set -euo pipefail
            exec > >(tee "$logf") 2>&1

            section "Removing old domain: $DOMAIN"
            rm -f "$NGINX_CONF_PATH" 2>/dev/null || true
            [[ -n "$NGINX_ENABLED_PATH" ]] && rm -f "$NGINX_ENABLED_PATH" 2>/dev/null || true
            certbot delete --cert-name "$DOMAIN" --non-interactive 2>/dev/null || true
            remove_ip_echo "$DOMAIN" || true
            nginx -t 2>/dev/null && systemctl reload nginx || true
            success "Old domain removed"

            DOMAIN="$_new"

            section "Setting up new domain: $DOMAIN"
            sync_frontend "$DOMAIN"
            write_nginx_http "$DOMAIN"
            get_ssl "$DOMAIN" "$EMAIL"
            write_nginx_https "$DOMAIN"
            [[ -d "$BACKEND_DIR" ]] && sync_backend || true
            setup_ip_echo "$DOMAIN" "$EMAIL" || true
        ) || { warn "Errors during switch — check $logf"; press_enter; return 0; }

        DOMAIN="$_new"
        save_conf
        print_summary "$DOMAIN"
        ;;

      *) info "Back to main menu." ;;
    esac

    press_enter
}

# ─── Option 5: Update from Repo ───────────────────────────────────────────────
opt_5_update_repo() {
    show_banner
    section "Option 5 — Update from Repository"

    # Determine which git repo to use as the reference for branch listing.
    # Priority: SCRIPT_DIR (where deploy.sh lives) if it's a git repo; else REPO_DIR.
    local src_dir="$REPO_DIR"
    if [[ -d "$SCRIPT_DIR/.git" ]] && [[ "$SCRIPT_DIR" != "$REPO_DIR" ]]; then
        src_dir="$SCRIPT_DIR"
    elif [[ ! -d "$REPO_DIR/.git" ]]; then
        warn "Repository not cloned yet. Run Option 1 to install first."
        press_enter; return 0
    fi

    local current_branch
    current_branch=$(git -C "$src_dir" branch --show-current 2>/dev/null || echo "unknown")

    echo -e "  Script dir:     ${DIM}${SCRIPT_DIR}${RESET}"
    echo -e "  Server repo:    ${DIM}${REPO_DIR}${RESET}"
    echo -e "  Remote:         ${DIM}${REPO_URL}${RESET}"
    echo -e "  Current branch: ${BOLD}${current_branch}${RESET}"
    echo -e "  Last commit:    ${DIM}$(git -C "$src_dir" log -1 --format='%h %s' 2>/dev/null)${RESET}"
    echo ""

    info "Fetching remote branch list…"
    git -C "$src_dir" fetch --quiet origin 2>/dev/null \
        || warn "Could not reach remote — using cached branch list"

    local branches=()
    while IFS= read -r b; do
        [[ -z "$b" ]] && continue
        branches+=("$b")
    done < <(git -C "$src_dir" branch -r 2>/dev/null \
        | grep -v '\->' | sed 's|[[:space:]]*origin/||')

    if [[ "${#branches[@]}" -gt 0 ]]; then
        echo -e "  ${BOLD}Available branches:${RESET}"
        local i=1
        for b in "${branches[@]}"; do
            local marker=""
            [[ "$b" == "$current_branch" ]] && marker=" ${DIM}← current${RESET}"
            printf "    %s%d)%s  %s%s\n" "${CYAN}" "$i" "${RESET}" "$b" "$marker"
            ((i++))
        done
        echo ""
    fi

    echo -ne "  Branch number or name (Enter = keep ${DIM}[${current_branch}]${RESET}, 0 to cancel): "
    read -r _input
    [[ "$_input" == "0" ]] && return 0

    local target_branch="$current_branch"
    if [[ -n "$_input" ]]; then
        if [[ "$_input" =~ ^[0-9]+$ ]] && (( _input >= 1 && _input <= ${#branches[@]} )); then
            target_branch="${branches[$(( _input - 1 ))]}"
        else
            target_branch="$_input"
        fi
    fi

    echo ""
    echo -e "  Target:  ${BOLD}${target_branch}${RESET}"
    ask_proceed "Proceed" || return 0

    mkdir -p "$LOG_DIR"
    local logf="$LOG_DIR/update_$(date +%Y%m%d_%H%M%S).log"
    info "Logging to: $logf"

    # ── Self-update FIRST, OUTSIDE the subshell so we can exit the whole program ──
    # bash runs the in-memory copy of this script parsed at launch; a freshly pulled
    # deploy.sh does NOT hot-reload. If we kept going in this same process, the apply
    # steps below (write_nginx_https, sync_*) would still call the OLD functions, so a
    # just-pulled fix to any config writer would silently not take effect this run.
    # So: pull the dir the running script lives in, and if THIS file's commit changed,
    # stop and make the operator re-launch; the new code then applies on the next run.
    # Watch SCRIPT_DIR unconditionally (even when == REPO_DIR) — it's where $0 lives.
    if [[ -d "$SCRIPT_DIR/.git" ]]; then
        local _self_before _self_after
        _self_before=$(git -C "$SCRIPT_DIR" rev-parse HEAD 2>/dev/null || echo none)
        info "Pulling script directory: $SCRIPT_DIR"
        if git -C "$SCRIPT_DIR" fetch origin \
           && git -C "$SCRIPT_DIR" checkout "$target_branch" \
           && git -C "$SCRIPT_DIR" reset --hard "origin/$target_branch"; then
            success "Script dir updated: $(git -C "$SCRIPT_DIR" log -1 --format='%h %s')"
        else
            warn "Could not update script dir — check connectivity / branch name."
            press_enter; return 0
        fi
        _self_after=$(git -C "$SCRIPT_DIR" rev-parse HEAD 2>/dev/null || echo none)
        if [[ "$_self_before" != "$_self_after" ]]; then
            echo ""
            warn "deploy.sh itself changed: ${_self_before:0:7} → ${_self_after:0:7}"
            echo -e "  ${BOLD}Bash is still running the old in-memory copy.${RESET} Re-launch deploy.sh and run"
            echo -e "  Option 5 again to apply the new code (sync frontend/backend/nginx)."
            echo -e "  ${DIM}Continuing now would apply with the old code instead of what was just pulled.${RESET}"
            press_enter
            exit 0
        fi
        info "deploy.sh unchanged — applying with the current code."
    fi

    (
        set -euo pipefail
        exec > >(tee "$logf") 2>&1

        # ── Pull server repo: /opt/office-tools/repo ───────────────────────────
        if [[ -d "$REPO_DIR/.git" ]]; then
            info "Pulling server repo: $REPO_DIR"
            git -C "$REPO_DIR" fetch origin
            git -C "$REPO_DIR" checkout "$target_branch"
            git -C "$REPO_DIR" reset --hard "origin/$target_branch"
            success "Server repo updated: $(git -C "$REPO_DIR" log -1 --format='%h %s')"
        elif [[ -d "$SCRIPT_DIR/.git" ]]; then
            # Server repo doesn't exist yet — seed it from SCRIPT_DIR or clone fresh
            info "Server repo not found — cloning from remote…"
            mkdir -p "$(dirname "$REPO_DIR")"
            git clone --branch "$target_branch" "$REPO_URL" "$REPO_DIR"
            success "Server repo cloned: $(git -C "$REPO_DIR" log -1 --format='%h %s')"
        fi

        load_conf
        sync_frontend "${DOMAIN:-}"

        # Sync backend if installed
        [[ -d "$BACKEND_DIR" ]] && sync_backend || true

        # Sync yt-server if installed
        [[ -d "$YT_SERVER_DIR" ]] && sync_yt_server || true

        # Refresh nginx config so new location blocks (e.g. /yt-api/) are always picked up.
        # Re-write the full config from the current deploy.sh template — safe because the
        # config is generated from a template with no manual customisations.
        if systemctl is-active --quiet nginx 2>/dev/null && [[ -n "${DOMAIN:-}" ]]; then
            local ssl_cert="/etc/letsencrypt/live/${DOMAIN}/fullchain.pem"
            if [[ -f "$ssl_cert" ]]; then
                info "Refreshing nginx HTTPS config for ${DOMAIN}…"
                write_nginx_https "$DOMAIN"
            elif [[ -f "$NGINX_CONF_PATH" ]]; then
                info "Refreshing nginx HTTP config for ${DOMAIN}…"
                write_nginx_http "$DOMAIN"
            fi
            success "nginx config refreshed and reloaded"
        elif systemctl is-active --quiet nginx 2>/dev/null; then
            systemctl reload nginx
            success "nginx reloaded"
        fi
    ) || { warn "Update failed — check $logf"; press_enter; return 0; }

    load_conf
    if [[ -n "$DOMAIN" ]]; then
        success "Updated to branch '${target_branch}' — https://${DOMAIN}"
    else
        success "Updated to branch '${target_branch}'"
    fi
    press_enter
}

# ─── Option 6: Admin Tasks ────────────────────────────────────────────────────
opt_6_admin_tasks() {
    while true; do
        show_banner
        load_conf
        section "Option 6 — Admin Tasks"

        echo -e "    ${BOLD}a)${RESET}  Service Status       ${DIM}detailed status for all services${RESET}"
        echo -e "    ${BOLD}b)${RESET}  Restart All Services ${DIM}nginx · api · pot-provider · yt-server${RESET}"
        echo -e "    ${BOLD}c)${RESET}  URLs & Ports         ${DIM}list all tool URLs, APIs, and listening ports${RESET}"
        echo -e "    ${BOLD}d)${RESET}  Backup Database      ${DIM}back up SQLite DB → /opt/office-tools/backups/${RESET}"
        echo -e "    ${BOLD}e)${RESET}  Restore Database     ${DIM}restore from a previous backup${RESET}"
        echo -e "    ${BOLD}f)${RESET}  Clean Old Logs       ${DIM}delete deploy logs older than 30 days${RESET}"
        echo -e "    ${BOLD}g)${RESET}  Purge Temp Files     ${DIM}file-share uploads${RESET}"
        echo -e "    ${BOLD}h)${RESET}  Update yt-server     ${DIM}sync from repo, update yt-dlp + PO-token provider, restart${RESET}"
        echo -e "    ${BOLD}i)${RESET}  Feedback emails      ${DIM}set / update notification email addresses${RESET}"
        echo -e "    ${BOLD}j)${RESET}  YouTube cookies      ${DIM}install / test / remove cookies.txt for yt-server${RESET}"
        echo -e "  ${DIM}  ──────────────────────────────────────────────${RESET}"
        echo -e "    ${BOLD}0)${RESET}  Back"
        echo ""
        echo -ne "  Choose [a-j / 0]: "; read -r _sub
        echo ""

        case "${_sub,,}" in
            a)  _admin_service_status   ;;
            b)  _admin_restart_all      ;;
            c)  _admin_list_urls        ;;
            d)  _admin_backup_db        ;;
            e)  _admin_restore_db       ;;
            f)  _admin_clean_logs       ;;
            g)  _admin_purge_temp       ;;
            h)  _admin_update_yt_server  ;;
            i)  _admin_feedback_email   ;;
            j)  _admin_configure_cookies ;;
            0)  return 0                ;;
            *)  warn "Invalid: $_sub"   ;;
        esac
    done
}

_admin_service_status() {
    section "Service Status"
    local svcs=("nginx" "office-tools-api" "office-tools-cobalt" "office-tools-pot")
    for svc in "${svcs[@]}"; do
        if ! systemctl list-unit-files "${svc}.service" &>/dev/null 2>&1 \
           || ! systemctl list-unit-files "${svc}.service" 2>/dev/null | grep -q "^${svc}"; then
            echo -e "  ${DIM}○ %-22s not installed${RESET}" "$svc"
            continue
        fi
        if systemctl is-active --quiet "$svc" 2>/dev/null; then
            local uptime mem pid
            pid=$(systemctl show -p MainPID --value "$svc" 2>/dev/null || echo "")
            uptime=$(systemctl show -p ActiveEnterTimestamp --value "$svc" 2>/dev/null \
                     | sed 's/ [A-Z]*$//' || echo "")
            mem=""
            if [[ -n "$pid" ]] && [[ "$pid" != "0" ]]; then
                mem=$(ps -o rss= -p "$pid" 2>/dev/null | awk '{printf "%.1f MB", $1/1024}')
            fi
            printf "  ${GREEN}●${RESET} %-22s ${GREEN}running${RESET}" "$svc"
            [[ -n "$uptime" ]] && printf "  since %s" "$uptime"
            [[ -n "$mem"    ]] && printf "  |  mem: %s" "$mem"
            echo ""
        else
            local reason
            reason=$(systemctl show -p ActiveState --value "$svc" 2>/dev/null || echo "stopped")
            printf "  ${YELLOW}●${RESET} %-22s ${YELLOW}%s${RESET}\n" "$svc" "$reason"
            local last_err
            last_err=$(journalctl -u "$svc" -n 3 --no-pager --output=cat 2>/dev/null | tail -1)
            [[ -n "$last_err" ]] && echo -e "    ${DIM}Last log: ${last_err}${RESET}"
        fi
    done
    echo ""

    # Port listener table
    echo -e "  ${BOLD}Listening ports:${RESET}"
    echo -e "  ────────────────────────────────────────"
    for port_svc in "80:nginx (HTTP)" "443:nginx (HTTPS)" "3001:api-server" "9000:yt-server (YouTube downloads)" "${POT_PORT}:PO-token provider (bgutil)"; do
        local port="${port_svc%%:*}" label="${port_svc#*:}"
        if ss -tlnp 2>/dev/null | grep -q ":${port}\b"; then
            echo -e "  ${GREEN}●${RESET} :${port}  ${label}"
        else
            echo -e "  ${DIM}○ :${port}  ${label} (not listening)${RESET}"
        fi
    done
    echo ""
    press_enter
}

_admin_restart_all() {
    section "Restarting All Services"
    local svcs=("nginx" "office-tools-api" "office-tools-pot" "office-tools-cobalt")
    local any=false
    for svc in "${svcs[@]}"; do
        if systemctl list-unit-files "${svc}.service" 2>/dev/null | grep -q "^${svc}"; then
            any=true
            echo -ne "  Restarting ${svc}… "
            if systemctl restart "$svc" 2>/dev/null; then
                echo -e "${GREEN}OK${RESET}"
            else
                echo -e "${YELLOW}FAILED${RESET}"
                warn "Check: journalctl -u $svc -n 20"
            fi
        fi
    done
    $any || warn "No managed services found — run Option 1 to install first."
    echo ""
    press_enter
}

_admin_list_urls() {
    load_conf
    section "URLs, APIs & Ports"

    if [[ -z "$DOMAIN" ]]; then
        warn "No domain configured yet — run Option 2 first."
        echo -e "  ${DIM}Services are running locally:${RESET}"
    fi

    local base="https://${DOMAIN:-<your-domain>}"

    echo -e "  ${BOLD}Frontend (nginx → $WEB_ROOT)${RESET}"
    echo -e "  ${CYAN}·${RESET} Main site      : ${base}/"
    echo -e "  ${CYAN}·${RESET} All tools      : ${base}/tools/"
    echo ""

    echo -e "  ${BOLD}Reverse-proxy routes (nginx)${RESET}"
    echo -e "  ${CYAN}·${RESET} API             : ${base}/tools-api/          → 127.0.0.1:3001"
    [[ -d "$YT_SERVER_DIR" ]] && \
    echo -e "  ${CYAN}·${RESET} YT Download API : ${base}/yt-api/             → 127.0.0.1:9000"
    echo ""

    echo -e "  ${BOLD}Internal services${RESET}"
    echo -e "  ${DIM}·${RESET} nginx           : :80 (HTTP) / :443 (HTTPS)"
    echo -e "  ${DIM}·${RESET} api server      : 127.0.0.1:3001"
    [[ -d "$YT_SERVER_DIR" ]] && \
    echo -e "  ${DIM}·${RESET} yt-server       : 127.0.0.1:9000"
    [[ -d "$POT_SERVER_DIR" ]] && \
    echo -e "  ${DIM}·${RESET} PO-token provider: 127.0.0.1:${POT_PORT}  ${DIM}(bgutil — YouTube bot-check bypass)${RESET}"
    echo ""

    echo -e "  ${BOLD}Pages${RESET}"
    echo -e "  ${DIM}·${RESET} ${base}/"
    echo -e "  ${DIM}·${RESET} ${base}/pages/donate.html"
    echo ""

    echo -e "  ${BOLD}Backend-dependent tools${RESET}"
    for t in "url-shortener" "pastebin" "file-share"; do
        echo -e "  ${DIM}·${RESET} ${base}/tools/${t}/"
    done
    echo ""

    echo -e "  ${BOLD}Sample tools (browser-local, no backend)${RESET}"
    for t in "currency" "password-generator" "qr-generator" "hash-generator" \
             "ip-location" "my-ip" "loan-calculator" "unit-converter" \
             "ai-token-counter" "yt-downloader"; do
        echo -e "  ${DIM}·${RESET} ${base}/tools/${t}/"
    done
    echo ""

    echo -e "  ${BOLD}API health checks${RESET}"
    echo -e "  ${DIM}·${RESET} api server      : ${base}/tools-api/health"
    [[ -d "$YT_SERVER_DIR" ]] && \
    echo -e "  ${DIM}·${RESET} yt-server       : ${base}/yt-api/health"
    echo ""

    press_enter
}

_admin_backup_db() {
    local backup_dir="/opt/office-tools/backups"
    local db_file="/opt/office-tools/data/tools.db"
    mkdir -p "$backup_dir"
    section "Backup Database"

    if [[ ! -f "$db_file" ]]; then
        warn "SQLite database not found at $db_file — backend not installed or not yet started."
        press_enter; return 0
    fi

    local ts; ts=$(date +%Y%m%d_%H%M%S)
    local backup_file="${backup_dir}/tools_backup_${ts}.db"

    info "Copying SQLite database (tools.db)…"
    cp "$db_file" "$backup_file" \
        && success "Backup saved: $backup_file" \
        || warn "Backup failed — check disk space and permissions"

    # Show last 5 backups
    echo ""
    echo -e "  ${BOLD}Recent backups:${RESET}"
    ls -lh "${backup_dir}"/tools_backup_*.db 2>/dev/null \
        | tail -5 \
        | awk '{printf "  · %s  (%s)\n", $NF, $5}' \
        || echo -e "  ${DIM}(none)${RESET}"
    echo ""
    press_enter
}

_admin_restore_db() {
    local backup_dir="/opt/office-tools/backups"
    local db_file="/opt/office-tools/data/tools.db"
    section "Restore Database"

    # List backups
    local backups=()
    while IFS= read -r f; do
        [[ -f "$f" ]] && backups+=("$f")
    done < <(ls -t "${backup_dir}"/tools_backup_*.db 2>/dev/null)

    if [[ "${#backups[@]}" -eq 0 ]]; then
        warn "No backups found in ${backup_dir}."
        press_enter; return 0
    fi

    echo -e "  ${BOLD}Available backups:${RESET}"
    local i=1
    for f in "${backups[@]}"; do
        local sz; sz=$(du -sh "$f" 2>/dev/null | cut -f1)
        printf "    ${CYAN}%d)${RESET}  %-50s %s\n" "$i" "$(basename "$f")" "$sz"
        ((i++))
    done
    echo ""
    echo -ne "  Select backup number (0 to cancel): "
    read -r _sel
    [[ "$_sel" == "0" ]] || [[ -z "$_sel" ]] && return 0

    if ! [[ "$_sel" =~ ^[0-9]+$ ]] || (( _sel < 1 || _sel > ${#backups[@]} )); then
        warn "Invalid selection."; press_enter; return 0
    fi

    local chosen="${backups[$(( _sel - 1 ))]}"
    echo ""
    echo -e "  ${YELLOW}${BOLD}WARNING: This will overwrite the current database with:${RESET}"
    echo -e "  ${YELLOW}$(basename "$chosen")${RESET}"
    echo ""
    ask_proceed "Proceed" || return 0

    info "Stopping API server…"
    systemctl stop office-tools-api 2>/dev/null || true
    sleep 1

    info "Restoring backup…"
    cp "$chosen" "$db_file" \
        && success "Restore complete" \
        || warn "Restore failed — check the backup file integrity"

    chown root:root "$db_file" 2>/dev/null || true

    info "Restarting API server…"
    systemctl start office-tools-api 2>/dev/null \
        && success "API server running" \
        || warn "API server failed to restart — check: journalctl -u office-tools-api -n 20"
    press_enter
}

_admin_clean_logs() {
    section "Clean Old Logs"
    mkdir -p "$LOG_DIR"

    local count
    count=$(find "$LOG_DIR" -type f -name "*.log" -mtime +30 2>/dev/null | wc -l)
    echo -e "  Log directory : ${LOG_DIR}"
    echo -e "  Total size    : $(du -sh "$LOG_DIR" 2>/dev/null | cut -f1)"
    echo -e "  Logs > 30 days: ${count} file(s)"
    echo ""

    if [[ "$count" -eq 0 ]]; then
        info "No logs older than 30 days — nothing to clean."
        press_enter; return 0
    fi

    ask_proceed "Delete ${count} log file(s) older than 30 days" || return 0
    find "$LOG_DIR" -type f -name "*.log" -mtime +30 -delete
    success "Deleted ${count} old log file(s)."

    # Also rotate nginx logs if present
    if [[ -d /var/log/nginx ]]; then
        local nginx_old
        nginx_old=$(find /var/log/nginx -type f -name "*.log.*" -mtime +30 2>/dev/null | wc -l)
        if [[ "$nginx_old" -gt 0 ]]; then
            find /var/log/nginx -type f -name "*.log.*" -mtime +30 -delete
            success "Deleted ${nginx_old} old nginx rotated log(s)."
        fi
    fi

    press_enter
}

_admin_purge_temp() {
    section "Purge Temp Files"
    local purged=false

    # ── File-share uploads ─────────────────────────────────────────────────
    local uploads_dir="/opt/office-tools/data/uploads"
    if [[ -d "$uploads_dir" ]]; then
        local fs_count fs_size
        fs_count=$(find "$uploads_dir" -type f 2>/dev/null | wc -l)
        fs_size=$(du -sh "$uploads_dir" 2>/dev/null | cut -f1 || echo "0")

        echo -e "  ${BOLD}File-share uploaded files${RESET}  (${uploads_dir})"
        echo -e "  Files : ${fs_count}   Size : ${fs_size}"
        echo -e "  ${DIM}Note: these are files shared via the File Share tool.${RESET}"
        echo -e "  ${YELLOW}Warning: deleting removes files from active shares.${RESET}"

        if [[ "$fs_count" -gt 0 ]]; then
            echo -ne "  Delete ALL uploaded files? [y/N]: "; read -r _r; _r="${_r:-N}"
            if [[ "${_r,,}" == "y" ]]; then
                find "$uploads_dir" -type f -delete 2>/dev/null
                success "Deleted ${fs_count} uploaded file(s)."
                purged=true
            fi
        fi
    else
        echo -e "  ${DIM}File-share uploads dir not found — backend not installed.${RESET}"
    fi
    echo ""

    $purged || info "Nothing was deleted."
    press_enter
}

_admin_feedback_email() {
    section "Feedback Notification Emails"
    if [[ ! -f "$BACKEND_DIR/.env" ]]; then
        warn "Backend not installed — run Option 2 first."
        press_enter; return 0
    fi

    local cur1 cur2
    cur1=$(grep '^NOTIFY_EMAIL=' "$BACKEND_DIR/.env" 2>/dev/null \
        | cut -d= -f2- | tr -d '"' | tr -d "'")
    cur2=$(grep '^NOTIFY_EMAIL_2=' "$BACKEND_DIR/.env" 2>/dev/null \
        | cut -d= -f2- | tr -d '"' | tr -d "'")

    echo -e "  ${DIM}Current primary  : ${cur1:-(not set)}${RESET}"
    echo -e "  ${DIM}Current secondary: ${cur2:-(not set)}${RESET}"
    echo ""
    echo -e "  ${DIM}Leave blank to keep current value. Enter '-' to clear.${RESET}"
    echo ""

    echo -ne "  Primary email: "; read -r _e1
    echo -ne "  Secondary email (optional): "; read -r _e2

    [[ "$_e1" == "-" ]] && _e1=""
    [[ "$_e2" == "-" ]] && _e2=""
    [[ -z "$_e1" ]] && _e1="$cur1"
    [[ -z "$_e2" ]] && _e2="$cur2"

    _update_notify_env "$_e1" "$_e2"
    systemctl restart office-tools-api 2>/dev/null \
        && success "Feedback emails updated and API server restarted." \
        || warn "Could not restart API server — check: journalctl -u office-tools-api -n 10"
    press_enter
}

_admin_update_yt_server() {
    section "Update yt-server"
    if [[ ! -d "$YT_SERVER_DIR" ]]; then
        warn "yt-server not installed — run Option 1 first."
        press_enter; return 0
    fi

    ask_proceed "Sync yt-server from repo, update yt-dlp + PO-token provider, and restart services" || return 0

    install_ytdlp
    setup_pot_provider
    sync_yt_server

    systemctl is-active --quiet office-tools-cobalt \
        && success "yt-server updated and running" \
        || warn "yt-server restart failed — check: journalctl -u office-tools-cobalt -n 20"
    press_enter
}

# ─── Admin: YouTube cookies ───────────────────────────────────────────────────
# The one step that cannot be automated away: Google gates the login behind a human
# (CAPTCHA/2FA, worse from a datacenter IP). Everything AFTER the export is done here
# so the operator never has to hand-run install/grep/echo/systemctl.
#
# Option 5 in this menu prints the full create/renew guide; _cookie_howto() below is
# the single copy of those instructions.
_admin_configure_cookies() {
    section "Configure YouTube cookies"

    if [[ ! -d "$YT_SERVER_DIR" ]]; then
        warn "yt-server not installed — run Option 1 first."
        press_enter; return 0
    fi

    local cookie_file="${YT_SERVER_DIR}/cookies.txt"
    local status_file="${YT_SERVER_DIR}/cookies.status"

    echo -e "  Current state:"
    if [[ -f "$cookie_file" ]]; then
        echo -e "    ${BOLD}file:${RESET}   $cookie_file  ${DIM}($(wc -l < "$cookie_file") lines, $(stat -c '%U:%G %a' "$cookie_file"))${RESET}"
        [[ -f "$status_file" ]] \
            && echo -e "    ${BOLD}status:${RESET} $(head -n1 "$status_file")" \
            || echo -e "    ${BOLD}status:${RESET} ${DIM}not probed yet (keep-alive cron has not run)${RESET}"
    else
        echo -e "    ${DIM}no cookie file installed${RESET}"
    fi
    echo ""
    echo -e "  ${BOLD}1)${RESET} Paste cookies.txt content"
    echo -e "  ${BOLD}2)${RESET} Import from a path on this server"
    echo -e "  ${BOLD}3)${RESET} Test now ${DIM}(run the keep-alive probe and show the result)${RESET}"
    echo -e "  ${BOLD}4)${RESET} Remove cookies ${DIM}(back to PO-token only)${RESET}"
    echo -e "  ${BOLD}5)${RESET} How do I create / renew these? ${DIM}step-by-step guide${RESET}"
    echo -e "  ${BOLD}0)${RESET} Back"
    echo ""
    echo -ne "  Choose [1-5 / 0]: "; read -r _ck
    echo ""

    local tmp_file
    case "$_ck" in
        1)
            if [[ ! -f "$cookie_file" ]]; then
                echo -e "  ${DIM}No cookie file yet. If you have not exported one, pick 5 first.${RESET}"
                echo ""
            fi
            echo -e "  Paste the whole ${BOLD}cookies.txt${RESET} below (it starts with a"
            echo -e "  ${DIM}# Netscape HTTP Cookie File${RESET} line), then press Enter and type"
            echo -e "  a line containing only ${BOLD}EOF${RESET} to finish:"
            echo ""
            tmp_file="$(mktemp)"
            local _line
            while IFS= read -r _line; do
                [[ "$_line" == "EOF" ]] && break
                printf '%s\n' "$_line" >> "$tmp_file"
            done
            ;;
        2)
            echo -ne "  Path to cookies.txt on this server: "; read -r _src
            [[ -f "${_src:-}" ]] || { warn "No such file: ${_src:-}"; press_enter; return 0; }
            tmp_file="$(mktemp)"
            cp "$_src" "$tmp_file" || { warn "Could not read $_src"; rm -f "$tmp_file"; press_enter; return 0; }
            ;;
        3)
            _cookie_probe
            press_enter; return 0
            ;;
        5)
            _cookie_howto
            press_enter; return 0
            ;;
        4)
            ask_proceed "Remove the cookie file and unset YTDLP_COOKIES" || return 0
            rm -f "$cookie_file" "$status_file"
            sed -i '/^[[:space:]]*YTDLP_COOKIES=/d' "${YT_SERVER_DIR}/.env" 2>/dev/null || true
            systemctl restart office-tools-cobalt 2>/dev/null || true
            success "Cookies removed — yt-server restarted (PO-token only)"
            press_enter; return 0
            ;;
        *) return 0 ;;
    esac

    # Sanity-check before installing: a truncated paste or an HTML error page saved as
    # cookies.txt fails silently at download time, which is the hardest kind to debug.
    if ! grep -qi 'youtube\.com' "$tmp_file"; then
        warn "No youtube.com entries found — that does not look like a YouTube cookies.txt."
        rm -f "$tmp_file"; press_enter; return 0
    fi
    # Netscape format is TAB-separated, 7 fields. Some terminals and SSH clients turn
    # pasted TABs into spaces; that file installs fine and then fails inside yt-dlp with
    # an error that says nothing about tabs. Catch it here instead.
    if ! awk -F'\t' '$0 !~ /^#/ && NF >= 7 { found = 1 } END { exit !found }' "$tmp_file"; then
        warn "No tab-separated cookie lines found."
        echo -e "  ${DIM}Netscape cookies.txt uses TAB separators. A terminal paste can convert${RESET}"
        echo -e "  ${DIM}them to spaces — copy the file to the server and use option 2 instead.${RESET}"
        rm -f "$tmp_file"; press_enter; return 0
    fi

    # 600 www-data: yt-dlp REWRITES this file as it rotates the session, so the service
    # user must own it — a root-owned file makes every rotation fail silently.
    install -o www-data -g www-data -m 600 "$tmp_file" "$cookie_file" \
        || { warn "Could not install $cookie_file"; rm -f "$tmp_file"; press_enter; return 0; }
    rm -f "$tmp_file" "$status_file"

    env_ensure "${YT_SERVER_DIR}/.env" YTDLP_COOKIES "$cookie_file"
    chown www-data:www-data "${YT_SERVER_DIR}/.env" 2>/dev/null || true
    setup_cookie_keepalive

    systemctl restart office-tools-cobalt 2>/dev/null || true
    sleep 2
    success "Cookies installed ($(wc -l < "$cookie_file") lines) and yt-server restarted"
    echo ""
    _cookie_probe
    press_enter
}

# The create/renew guide. Printed on demand (Option 6 → j → 5) rather than dumped into
# the menu, because it is long and only needed twice a year.
_cookie_howto() {
    section "How to create / renew YouTube cookies"
    cat << 'HOWTOEOF'
  WHY THIS IS NEEDED
  ──────────────────
  YouTube answers datacenter/VPS IPs with "Sign in to confirm you're not a
  bot". The PO-token provider (office-tools-pot) handles most of that, but on a
  flagged IP YouTube also wants a logged-in session — that is what cookies.txt
  is. It cannot be generated on the server: Google's login is deliberately
  human-gated (CAPTCHA/2FA), and it is stricter still from a datacenter IP.
  So: export on your own computer, paste here.

  STEP 1 — MAKE A "BURNER" GOOGLE ACCOUNT
  ───────────────────────────────────────
  A burner (= throwaway, disposable) account is a NEW Google account made only
  for this job. Any name, no recovery details you care about, nothing else
  signed in to it, and losing it tomorrow costs you nothing.

  Never use your own Gmail. Two reasons:
    · YouTube flags — and sometimes bans — accounts whose session is used for
      server-side downloading.
    · cookies.txt IS a working login. It sits on this server; anyone who can
      read the file is signed in as that account. It is stored 600 www-data,
      but that is a burner account's job, not your real one's.

  Create it at accounts.google.com, then visit youtube.com once so the account
  has a normal YouTube session.

  STEP 2 — EXPORT THE COOKIE FILE (pick ONE route)
  ────────────────────────────────────────────────
  Route A — private window + extension   [RECOMMENDED]
    1. Install the "Get cookies.txt LOCALLY" browser extension, and allow it
       to run in private windows.
    2. Open a PRIVATE / INCOGNITO window.
    3. Log into youtube.com with the BURNER account.
    4. Open any ordinary video, e.g.
HOWTOEOF
    echo "         ${YTCOOKIE_PROBE_URL:-https://www.youtube.com/watch?v=J6VMJLSNAHk}"
    cat << 'HOWTOEOF'
    5. Click the extension -> Export -> save cookies.txt (Netscape format).
    6. CLOSE the private window WITHOUT logging out.

    Why private: nothing touches that session afterwards, so the cookies you
    exported stay valid. A session you keep browsing with has its cookies
    rotated by the browser and the exported copy dies within hours.

  Route B — let yt-dlp export it (no extension)
    1. Use a NORMAL window — not private. This route reads the browser's
       on-disk cookie database, and private-window cookies are memory-only,
       so they are invisible to it.
    2. Best in a Firefox profile kept only for the burner account, so your
       everyday browsing does not rotate the session away.
    3. Log in as the burner, then CLOSE Firefox (do not log out).
    4. Run:
HOWTOEOF
    echo "         yt-dlp --cookies-from-browser firefox --cookies cookies.txt \\"
    echo "                --skip-download \"${YTCOOKIE_PROBE_URL:-https://www.youtube.com/watch?v=J6VMJLSNAHk}\""
    cat << 'HOWTOEOF'
    Firefox, not Chrome: Chrome's app-bound cookie encryption commonly breaks
    --cookies-from-browser chrome.

  THE ONE RULE THAT DECIDES WHETHER THIS WORKS
  ────────────────────────────────────────────
  Never log the burner out, and do not keep browsing YouTube in that session.
  Logging out invalidates the session on Google's side, which kills the
  exported file too — that is the #1 reason server cookies "work for an hour
  and then die".

  STEP 3 — INSTALL IT HERE
  ────────────────────────
  Open cookies.txt in a text editor, copy all of it, come back to this menu
  and choose 1) Paste cookies.txt content. Paste, then a line with only EOF.
  This script validates it, installs it 600 www-data, sets YTDLP_COOKIES in
  the yt-server .env, installs the keep-alive cron, restarts yt-server and
  runs a probe so you see immediately whether YouTube accepted it.

  (Already have the file on this server? Use 2) Import from a path instead.)

  RENEWING — WHEN AND HOW
  ───────────────────────
  Cookies last weeks, not forever. You do not have to watch for it:
    · a cron probe runs every 6 hours (ytcookie-keepalive.sh). It keeps the
      session rotating, and when Google finally rejects it the probe writes
      "expired" into cookies.status;
    · /health then reports "cookies":"file:expired", and the yt-downloader
      page shows an orange "cookies expired" warning next to the backend line;
    · option 3 here re-runs that probe on demand.
  To renew: repeat STEP 2 with the same burner account (log in again if it was
  signed out) and paste the new file over the old one with option 1.

  TROUBLESHOOTING
  ───────────────
    "file:missing"      YTDLP_COOKIES in .env points at a file that is gone.
    "file:unchecked"    installed, cron has not probed yet — use option 3.
    inconclusive probe  network/YouTube hiccup, or the probe video was
                        removed. The old status is kept on purpose. Override
                        the video with YTCOOKIE_PROBE_URL if needed.
    still bot-checked   confirm office-tools-pot is running and yt-dlp is
                        current (Option 6 -> h), then re-export the cookies.
HOWTOEOF
    echo ""
}

# Runs the keep-alive probe once (as www-data, exactly as cron will) and prints both
# its verdict and what /health now reports.
_cookie_probe() {
    local ka="${YT_SERVER_DIR}/ytcookie-keepalive.sh"
    if [[ -x "$ka" ]]; then
        info "Probing cookies with yt-dlp…"
        # Run as the service user so a rotated cookies.txt keeps www-data ownership.
        if command -v runuser &>/dev/null; then
            runuser -u www-data -- "$ka" 2>&1 | sed 's/^/    /' || true
        else
            su -s /bin/bash www-data -c "$ka" 2>&1 | sed 's/^/    /' || true
        fi
    else
        warn "Keep-alive script not found at $ka — run Option 6 → h to sync yt-server."
    fi
    # PORT is operator-editable in .env — do not assume 9000, or this reports a healthy
    # server as down on any box where it was changed.
    local port health
    port="$(sed -n 's/^[[:space:]]*PORT=//p' "${YT_SERVER_DIR}/.env" 2>/dev/null | tail -n1 | tr -d "\"' ")"
    port="${port:-9000}"
    health="$(curl -s --max-time 5 "http://127.0.0.1:${port}/health" 2>/dev/null || true)"
    if [[ -n "$health" ]]; then
        echo -e "  ${BOLD}/health:${RESET} ${health}"
    else
        warn "yt-server not answering on 127.0.0.1:${port} — check: journalctl -u office-tools-cobalt -n 30"
    fi
}

# ─── DEL: Delete ──────────────────────────────────────────────────────────────
opt_del_delete() {
    show_banner
    section "Delete — Remove Office Tools"

    echo -e "  ${RED}${BOLD}This will PERMANENTLY remove Office Tools from this server.${RESET}"
    echo ""

    # Locate undeploy.sh
    local _undeploy=""
    for _p in \
        "$SCRIPT_DIR/undeploy.sh" \
        "$REPO_DIR/undeploy.sh" \
        "/opt/office-tools/repo/undeploy.sh"; do
        [[ -f "$_p" ]] && _undeploy="$_p" && break
    done

    if [[ -z "$_undeploy" ]]; then
        die "undeploy.sh not found. Copy it next to deploy.sh and retry."
    fi

    info "Will run: $_undeploy"
    echo ""
    bash "$_undeploy"
}

# ─── Main loop ────────────────────────────────────────────────────────────────
[[ "$EUID" -ne 0 ]] && die "Run as root: sudo bash deploy.sh"
detect_os

while true; do
    show_banner
    show_status

    echo -e "  ${BOLD}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${RESET}"
    echo -e "    ${BOLD}1)${RESET}   Install / Update    ${DIM}packages · OS · pull latest code${RESET}"
    echo -e "    ${BOLD}2)${RESET}   Add Domain          ${DIM}configure domain · SSL · backend${RESET}"
    echo -e "    ${BOLD}3)${RESET}   Remove / Switch     ${DIM}remove or change active domain${RESET}"
    echo -e "    ${BOLD}5)${RESET}   Update from Repo    ${DIM}pull specific branch · restart services${RESET}"
    echo -e "    ${BOLD}6)${RESET}   Admin Tasks         ${DIM}status · restart · URLs · backup · cleanup${RESET}"
    echo -e "  ${DIM}  ──────────────────────────────────────────────${RESET}"
    echo -e "  ${RED}  DEL)${RESET} Delete              ${DIM}permanently remove Office Tools${RESET}"
    echo -e "    ${BOLD}0)${RESET}   Exit"
    echo -e "  ${BOLD}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${RESET}"
    echo ""
    echo -ne "  Choose [0-3 / 5-6 / del]: "; read -r _choice
    echo ""

    case "${_choice,,}" in
        1)   opt_1_install_update ;;
        2)   opt_2_add_domain     ;;
        3)   opt_3_remove_switch  ;;
        5)   opt_5_update_repo    ;;
        6)   opt_6_admin_tasks    ;;
        del) opt_del_delete; break ;;
        0)   echo -e "${DIM}Goodbye.${RESET}"; exit 0 ;;
        *)   warn "Invalid choice: $_choice" ;;
    esac
done
