# =============================================================================
# Office Tools — Config helpers — deploy.conf and .env
# Sourced by deploy.sh — not executable on its own.
# shellcheck shell=bash
# =============================================================================

# ─── Config helpers ────────────────────────────────────────────────────────────
DOMAIN=""; EMAIL=""; SETUP_BACKEND="n"

load_conf() {
    DOMAIN=""; EMAIL=""; SETUP_BACKEND="n"
    [[ -f "$DEPLOY_CONF" ]] && source "$DEPLOY_CONF" || true
}

save_conf() {
    mkdir -p "$(dirname "$DEPLOY_CONF")"
    cat > "$DEPLOY_CONF" << CONFEOF
# Office Tools deploy config — auto-generated by deploy.sh
DOMAIN="${DOMAIN}"
EMAIL="${EMAIL}"
SETUP_BACKEND="${SETUP_BACKEND}"
CONFEOF
    chmod 600 "$DEPLOY_CONF"
}

# Idempotent "this key must exist in that .env" — creates the file when missing, adds
# the key only when absent, and never touches a value the operator already set.
# Used instead of a truncating `cat > .env`, which would silently drop operator
# settings (YTDLP_COOKIES above all) on every re-run of the installer.
env_ensure() {
    local file="$1" key="$2" val="$3"
    if [[ ! -f "$file" ]]; then
        install -m 600 /dev/null "$file" || return 1
    fi
    grep -qE "^[[:space:]]*${key}=" "$file" || printf '%s=%s\n' "$key" "$val" >> "$file"
}


