# =============================================================================
# Office Tools — YouTube stack — ffmpeg, yt-dlp, PO-token, yt-server
# Sourced by deploy.sh — not executable on its own.
# shellcheck shell=bash
# =============================================================================

# ─── ffmpeg ───────────────────────────────────────────────────────────────────
# Required by yt-dlp for MP3 conversion and 1080p video muxing.
install_ffmpeg() {
    section "Installing ffmpeg"

    if command -v ffmpeg &>/dev/null; then
        info "ffmpeg already installed: $(ffmpeg -version 2>&1 | head -1 | awk '{print $3}')"
        return 0
    fi

    info "Installing ffmpeg…"
    if [[ "$OS_FAMILY" == "debian" ]]; then
        pkg_install ffmpeg
    else
        # RHEL-family: ffmpeg lives in RPM Fusion (not in default repos).
        # EPEL is already installed by install_base_packages.
        local rhel_ver
        rhel_ver=$(rpm -E %rhel 2>/dev/null || echo 9)
        local rpm_fusion="https://download1.rpmfusion.org/free/el/rpmfusion-free-release-${rhel_ver}.noarch.rpm"
        dnf install -y "$rpm_fusion" 2>/dev/null \
            || warn "RPM Fusion install failed — trying dnf without it"
        dnf install -y ffmpeg 2>/dev/null \
            || warn "ffmpeg unavailable — video processing may be limited"
    fi
    command -v ffmpeg &>/dev/null \
        && success "ffmpeg installed: $(ffmpeg -version 2>&1 | head -1)" \
        || warn "ffmpeg not found — install manually if needed"
}

# ─── yt-dlp + PO-token plugin ─────────────────────────────────────────────────
# Required by yt-server for video/audio downloading.
# bgutil-ytdlp-pot-provider is the yt-dlp-sanctioned bot-check bypass: YouTube now
# requires PO (Proof of Origin) tokens on most player clients, and this plugin
# fetches them automatically from the local token server (see setup_pot_provider).
install_ytdlp() {
    section "Installing yt-dlp + PO-token plugin"

    if command -v yt-dlp &>/dev/null; then
        info "yt-dlp found — updating…"
    else
        info "Installing yt-dlp…"
    fi

    # --break-system-packages needed on Ubuntu 22.04+ / Debian 12+ (PEP 668)
    # bgutil plugin needs yt-dlp ≥ 2025.05.22 — always updating both together keeps that true.
    pip3 install -U yt-dlp bgutil-ytdlp-pot-provider --break-system-packages 2>/dev/null \
        || pip3 install -U yt-dlp bgutil-ytdlp-pot-provider \
        || { warn "yt-dlp install failed — YouTube downloads will not work"; return 0; }

    # Weekly auto-update cron — YouTube changes constantly; a stale yt-dlp or plugin is
    # the #1 cause of bot-check 403s. Always rewritten so old installs get the new steps.
    local cron_file="/etc/cron.weekly/yt-dlp-update"
    cat > "$cron_file" << 'CRONEOF'
#!/bin/bash
# Auto-generated by deploy.sh — keeps YouTube download stack current.
pip3 install -U yt-dlp bgutil-ytdlp-pot-provider --break-system-packages 2>/dev/null \
    || pip3 install -U yt-dlp bgutil-ytdlp-pot-provider
# Rebuild the PO-token provider server to match the plugin version (script written by deploy.sh)
[[ -x /opt/office-tools/pot-update.sh ]] && /opt/office-tools/pot-update.sh
systemctl restart office-tools-cobalt 2>/dev/null || true
CRONEOF
    chmod +x "$cron_file"
    success "Weekly auto-update cron installed (yt-dlp + PO-token plugin + provider)"

    command -v yt-dlp &>/dev/null \
        && success "yt-dlp installed: $(yt-dlp --version)" \
        || warn "yt-dlp not found — install manually: pip3 install yt-dlp"
}

# ─── PO-token provider server (bgutil) ────────────────────────────────────────
# Runs BotGuard locally and mints PO tokens on demand (port 4416). The pip plugin
# installed by install_ytdlp auto-detects it at http://127.0.0.1:4416 — no yt-dlp
# flags needed. Server checkout is pinned to the installed plugin's version tag
# (plugin and server must match per upstream docs).
setup_pot_provider() {
    section "Setting up PO-token provider (bgutil, port ${POT_PORT})"

    # Node ≥ 20 required by the provider (install_nodejs puts a current LTS in place)
    local node_major
    node_major=$(node -v 2>/dev/null | sed 's/^v//' | cut -d. -f1)
    if [[ -z "$node_major" || "$node_major" -lt 20 ]]; then
        warn "Node.js ≥ 20 required for the PO-token provider (found: $(node -v 2>/dev/null || echo none)) — skipping"
        return 0
    fi

    # Match the server checkout to the installed pip plugin version
    local pot_ver
    pot_ver=$(pip3 show bgutil-ytdlp-pot-provider 2>/dev/null | awk '/^Version:/{print $2}')
    if [[ -z "$pot_ver" ]]; then
        warn "bgutil-ytdlp-pot-provider pip plugin not installed — run install_ytdlp first; skipping"
        return 0
    fi

    if [[ -d "$POT_SERVER_DIR/.git" ]]; then
        info "Updating provider checkout to v${pot_ver}…"
        git -C "$POT_SERVER_DIR" fetch --tags -q origin \
            || warn "git fetch failed — building current checkout"
    else
        info "Cloning bgutil-ytdlp-pot-provider…"
        rm -rf "$POT_SERVER_DIR"
        git clone -q https://github.com/Brainicism/bgutil-ytdlp-pot-provider.git "$POT_SERVER_DIR" \
            || { warn "clone failed — PO-token provider not installed (YouTube may serve bot-check 403s)"; return 0; }
    fi
    git -C "$POT_SERVER_DIR" -c advice.detachedHead=false checkout -q "$pot_ver" 2>/dev/null \
        || warn "tag ${pot_ver} not found — building default branch instead"

    info "Building provider (npm ci + tsc)…"
    ( cd "$POT_SERVER_DIR/server" && npm ci --silent && npx tsc ) \
        || { warn "provider build failed — check npm/node output above"; return 0; }
    chown -R www-data:www-data "$POT_SERVER_DIR"

    # Standalone updater used by the weekly cron (keeps server matched to the pip plugin)
    cat > /opt/office-tools/pot-update.sh << POTUPEOF
#!/bin/bash
# Auto-generated by deploy.sh — sync PO-token provider server to the pip plugin version.
set -e
ver=\$(pip3 show bgutil-ytdlp-pot-provider 2>/dev/null | awk '/^Version:/{print \$2}')
[[ -n "\$ver" && -d "$POT_SERVER_DIR/.git" ]] || exit 0
cd "$POT_SERVER_DIR"
git fetch --tags -q origin || exit 0
git -c advice.detachedHead=false checkout -q "\$ver" || exit 0
cd server && npm ci --silent && npx tsc
chown -R www-data:www-data "$POT_SERVER_DIR"
systemctl restart office-tools-pot 2>/dev/null || true
POTUPEOF
    chmod +x /opt/office-tools/pot-update.sh

    # Systemd service — the provider has no bind-address option (listens on all
    # interfaces), so block external access at the firewall when ufw is active.
    cat > /etc/systemd/system/office-tools-pot.service << POTEOF
[Unit]
Description=Office Tools — bgutil PO-token provider (YouTube bot-check bypass)
After=network.target

[Service]
Type=simple
User=www-data
Group=www-data
WorkingDirectory=${POT_SERVER_DIR}/server
ExecStart=/usr/bin/node build/main.js --port ${POT_PORT}
Environment=TZ=UTC
Restart=on-failure
RestartSec=5s
StandardOutput=journal
StandardError=journal

[Install]
WantedBy=multi-user.target
POTEOF

    if command -v ufw &>/dev/null && ufw status 2>/dev/null | grep -q "Status: active"; then
        ufw deny "${POT_PORT}/tcp" >/dev/null 2>&1 || true
        info "ufw: external access to :${POT_PORT} denied (provider is localhost-only by policy)"
    fi

    systemctl daemon-reload
    systemctl enable office-tools-pot >/dev/null 2>&1
    systemctl restart office-tools-pot

    sleep 2
    if curl -s -m 5 "http://127.0.0.1:${POT_PORT}/ping" | grep -q version; then
        success "PO-token provider running on http://127.0.0.1:${POT_PORT}/ (v${pot_ver})"
    else
        warn "PO-token provider not responding — check: journalctl -u office-tools-pot -n 30"
    fi
}

# ─── yt-server (YouTube download backend) ─────────────────────────────────────
setup_yt_server() {
    section "Setting up yt-server (YouTube download backend)"

    mkdir -p "$YT_SERVER_DIR"
    rsync -a "$REPO_DIR/yt-server/" "$YT_SERVER_DIR/"

    cd "$YT_SERVER_DIR" && npm install --omit=dev && cd /

    # Ensure .env — never rewrite it. setup_yt_server runs on EVERY Option 1, so a
    # truncating write here would wipe operator keys (YTDLP_COOKIES most of all, whose
    # loss looks exactly like YouTube blocking the server again, with nothing logged).
    env_ensure "$YT_SERVER_DIR/.env" PORT 9000
    chmod 600 "$YT_SERVER_DIR/.env"
    chmod +x "$YT_SERVER_DIR/ytcookie-keepalive.sh" 2>/dev/null || true
    chown -R www-data:www-data "$YT_SERVER_DIR"

    setup_cookie_keepalive

    # Create systemd service
    cat > /etc/systemd/system/office-tools-cobalt.service << COBEOF
[Unit]
Description=Office Tools — yt-server YouTube Download Server
After=network.target

[Service]
Type=simple
User=www-data
Group=www-data
WorkingDirectory=${YT_SERVER_DIR}
ExecStart=/usr/bin/node server.js
Environment=TZ=UTC
EnvironmentFile=-${YT_SERVER_DIR}/.env
Restart=on-failure
RestartSec=5s
StandardOutput=journal
StandardError=journal

[Install]
WantedBy=multi-user.target
COBEOF

    systemctl daemon-reload
    systemctl enable office-tools-cobalt
    systemctl restart office-tools-cobalt

    sleep 3
    if systemctl is-active --quiet office-tools-cobalt; then
        success "yt-server running on http://127.0.0.1:9000/"
    else
        warn "yt-server failed to start — check: journalctl -u office-tools-cobalt -n 30"
    fi
}

# ─── Cookie keep-alive (cron) ─────────────────────────────────────────────────
# yt-server's /health reads <cookie-dir>/cookies.status to report "file:ok" vs
# "file:expired"; nothing writes that file except this cron. Without it /health is
# stuck on "file:unchecked" and cookie expiry is invisible until downloads break.
# The probe also makes yt-dlp rotate the cookie file, which is what keeps a parked
# session alive between real downloads.
setup_cookie_keepalive() {
    local cron_file="/etc/cron.d/office-tools-ytcookie"
    local log_file="${LOG_DIR}/ytcookie-keepalive.log"

    mkdir -p "$LOG_DIR"
    touch "$log_file"
    chown www-data:www-data "$log_file" 2>/dev/null || true

    # Runs as www-data — the user yt-server runs as, so the rotated cookie file keeps
    # its owner. A root-run probe would leave a root-owned cookies.txt behind and the
    # service could no longer write to it.
    cat > "$cron_file" << CRONEOF
# Auto-generated by deploy.sh — YouTube cookie keep-alive + expiry reporting.
# No-op when YTDLP_COOKIES is unset in ${YT_SERVER_DIR}/.env.
SHELL=/bin/bash
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
17 */6 * * * www-data ${YT_SERVER_DIR}/ytcookie-keepalive.sh >> ${log_file} 2>&1
CRONEOF
    chmod 644 "$cron_file"

    cat > /etc/logrotate.d/office-tools-ytcookie << 'LOGROTEOF'
/var/log/office-tools/ytcookie-keepalive.log {
    monthly
    rotate 3
    missingok
    notifempty
    compress
    copytruncate
}
LOGROTEOF

    success "Cookie keep-alive cron installed (every 6h, logs → ${log_file})"
}

sync_yt_server() {
    [[ -d "$YT_SERVER_DIR" ]] || return 0
    section "Syncing yt-server (YouTube download backend)"
    # --exclude='.env' keeps operator settings (YTDLP_COOKIES) across syncs.
    rsync -a --exclude='.env' --exclude='cookies.txt' --exclude='cookies.status' \
        "$REPO_DIR/yt-server/" "$YT_SERVER_DIR/"
    cd "$YT_SERVER_DIR" && npm install --omit=dev && cd /
    chmod +x "$YT_SERVER_DIR/ytcookie-keepalive.sh" 2>/dev/null || true
    chown -R www-data:www-data "$YT_SERVER_DIR"
    setup_cookie_keepalive
    systemctl restart office-tools-cobalt 2>/dev/null || true
    success "yt-server synced and restarted"
}


